-- Per-user UI preference (visual theme, color mode, welcome launcher density).
-- Paste this entire file into the Supabase SQL Editor and run top to bottom.
-- Safe to re-run: CREATE IF NOT EXISTS / DROP POLICY IF EXISTS / CREATE OR REPLACE.
--
-- This is user-level data, not the tyapp_app_settings singleton.
-- Authenticated users may only SELECT / INSERT / UPDATE their own row.

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.tyapp_user_preference (
  tb_tyapp_usr_prf_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_usr_prf_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES public.tyapp_user (user_id),
  visual_theme text NOT NULL DEFAULT 'aero',
  color_mode text NOT NULL DEFAULT 'system',
  welcome_launcher_mode text NOT NULL DEFAULT 'auto',
  remarks text,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_user_preference_user_unique UNIQUE (user_id),
  CONSTRAINT tyapp_user_preference_visual_theme_chk
    CHECK (visual_theme IN ('aero', 'material')),
  CONSTRAINT tyapp_user_preference_color_mode_chk
    CHECK (color_mode IN ('light', 'dark', 'system')),
  CONSTRAINT tyapp_user_preference_welcome_launcher_mode_chk
    CHECK (welcome_launcher_mode IN ('auto', 'compact', 'detailed'))
);

CREATE INDEX IF NOT EXISTS tyapp_user_preference_user_idx
  ON public.tyapp_user_preference (user_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS tyapp_user_preference_set_updated_at
  ON public.tyapp_user_preference;
CREATE TRIGGER tyapp_user_preference_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_user_preference
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.tyapp_user_preference ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_user_preference FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE ON public.tyapp_user_preference TO authenticated;

DROP POLICY IF EXISTS tyapp_user_preference_select
  ON public.tyapp_user_preference;
DROP POLICY IF EXISTS tyapp_user_preference_insert
  ON public.tyapp_user_preference;
DROP POLICY IF EXISTS tyapp_user_preference_update
  ON public.tyapp_user_preference;

CREATE POLICY tyapp_user_preference_select
  ON public.tyapp_user_preference
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL);

CREATE POLICY tyapp_user_preference_insert
  ON public.tyapp_user_preference
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY tyapp_user_preference_update
  ON public.tyapp_user_preference
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL)
  WITH CHECK (user_id = auth.uid());
