-- Jaxfr Daily Log schema, RLS, and RPCs.
-- Paste this entire file into the Supabase SQL Editor and run top to bottom.
-- Safe to re-run: drops current tables/RPCs and recreates them.
-- Existing Daily Log rows are deleted. The App Feature registry row is kept.
--
-- Live databases that already have data: do NOT run this file.
-- Run daily-log.schema-rename.sql instead (ALTER RENAME, keeps rows).

-- ---------------------------------------------------------------------------
-- Reset
-- ---------------------------------------------------------------------------

DROP FUNCTION IF EXISTS public.tyapp_daily_log_create_from_template(date);
DROP FUNCTION IF EXISTS public.tyapp_daily_log_copy_previous_day(date);
DROP FUNCTION IF EXISTS public.tyapp_daily_log_item_soft_delete_single_record(uuid);
DROP FUNCTION IF EXISTS public.tyapp_daily_log_day_item_soft_delete_single_record(uuid);
DROP FUNCTION IF EXISTS public.tyapp_daily_log_template_item_soft_delete_single_record(uuid);
DROP FUNCTION IF EXISTS public.tyapp_daily_log_share_soft_delete_single_record(uuid);
DROP FUNCTION IF EXISTS public.tyapp_daily_log_share_enforce_group();

DROP TABLE IF EXISTS public.tyapp_daily_log_share CASCADE;
DROP TABLE IF EXISTS public.tyapp_daily_log_day CASCADE;
DROP TABLE IF EXISTS public.tyapp_daily_log_day_item CASCADE;
DROP TABLE IF EXISTS public.tyapp_daily_log_template_item CASCADE;
DROP TABLE IF EXISTS public.tyapp_daily_log_item CASCADE;

-- ---------------------------------------------------------------------------
-- Library: reusable item (name, emoji, colour)
-- ---------------------------------------------------------------------------

CREATE TABLE public.tyapp_daily_log_item (
  tb_tyapp_dl_itm_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_dl_itm_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES auth.users (id),
  item_text text NOT NULL,
  emoji text,
  colour_preset_key text NOT NULL DEFAULT 'slate',
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_daily_log_item_text_not_blank
    CHECK (length(btrim(item_text)) > 0),
  CONSTRAINT tyapp_daily_log_item_emoji_len
    CHECK (emoji IS NULL OR length(btrim(emoji)) BETWEEN 1 AND 32),
  CONSTRAINT tyapp_daily_log_item_colour_preset
    CHECK (colour_preset_key IN (
      'purple', 'blue', 'teal', 'green', 'gold', 'orange', 'red', 'slate'
    ))
);

CREATE UNIQUE INDEX tyapp_daily_log_item_user_name_uniq
  ON public.tyapp_daily_log_item (user_id, lower(btrim(item_text)))
  WHERE deleted_at IS NULL;

CREATE INDEX tyapp_daily_log_item_user_idx
  ON public.tyapp_daily_log_item (user_id)
  WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- Day occurrence: one library item on one date
-- ---------------------------------------------------------------------------

CREATE TABLE public.tyapp_daily_log_day_item (
  tb_tyapp_dl_day_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_dl_day_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES auth.users (id),
  item_id uuid NOT NULL REFERENCES public.tyapp_daily_log_item (tb_tyapp_dl_itm_id),
  log_date date NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  completed_at timestamptz,
  remarks text,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_daily_log_day_item_sort_order_nonneg
    CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX tyapp_daily_log_day_item_user_date_item_uniq
  ON public.tyapp_daily_log_day_item (user_id, log_date, item_id)
  WHERE deleted_at IS NULL;

CREATE INDEX tyapp_daily_log_day_item_user_date_sort_idx
  ON public.tyapp_daily_log_day_item (user_id, log_date, sort_order)
  WHERE deleted_at IS NULL;

CREATE INDEX tyapp_daily_log_day_item_user_completed_idx
  ON public.tyapp_daily_log_day_item (user_id, completed_at)
  WHERE deleted_at IS NULL AND completed_at IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Template pack: ordered library membership
-- ---------------------------------------------------------------------------

CREATE TABLE public.tyapp_daily_log_template_item (
  tb_tyapp_dl_tpl_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_dl_tpl_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES auth.users (id),
  item_id uuid NOT NULL REFERENCES public.tyapp_daily_log_item (tb_tyapp_dl_itm_id),
  sort_order integer NOT NULL DEFAULT 0,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_daily_log_template_item_sort_order_nonneg
    CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX tyapp_daily_log_template_item_user_item_uniq
  ON public.tyapp_daily_log_template_item (user_id, item_id)
  WHERE deleted_at IS NULL;

CREATE INDEX tyapp_daily_log_template_item_user_sort_idx
  ON public.tyapp_daily_log_template_item (user_id, sort_order)
  WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- updated_at
-- ---------------------------------------------------------------------------

DROP TRIGGER IF EXISTS tyapp_daily_log_item_set_updated_at
  ON public.tyapp_daily_log_item;
CREATE TRIGGER tyapp_daily_log_item_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_daily_log_item
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_daily_log_day_item_set_updated_at
  ON public.tyapp_daily_log_day_item;
CREATE TRIGGER tyapp_daily_log_day_item_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_daily_log_day_item
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_daily_log_template_item_set_updated_at
  ON public.tyapp_daily_log_template_item;
CREATE TRIGGER tyapp_daily_log_template_item_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_daily_log_template_item
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.tyapp_daily_log_item ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_daily_log_item FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE ON public.tyapp_daily_log_item TO authenticated;

ALTER TABLE public.tyapp_daily_log_day_item ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_daily_log_day_item FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE ON public.tyapp_daily_log_day_item TO authenticated;

ALTER TABLE public.tyapp_daily_log_template_item ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_daily_log_template_item FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE ON public.tyapp_daily_log_template_item TO authenticated;

DROP POLICY IF EXISTS tyapp_daily_log_item_select
  ON public.tyapp_daily_log_item;
DROP POLICY IF EXISTS tyapp_daily_log_item_insert
  ON public.tyapp_daily_log_item;
DROP POLICY IF EXISTS tyapp_daily_log_item_update
  ON public.tyapp_daily_log_item;
DROP POLICY IF EXISTS tyapp_daily_log_day_item_select
  ON public.tyapp_daily_log_day_item;
DROP POLICY IF EXISTS tyapp_daily_log_day_item_insert
  ON public.tyapp_daily_log_day_item;
DROP POLICY IF EXISTS tyapp_daily_log_day_item_update
  ON public.tyapp_daily_log_day_item;
DROP POLICY IF EXISTS tyapp_daily_log_template_item_select
  ON public.tyapp_daily_log_template_item;
DROP POLICY IF EXISTS tyapp_daily_log_template_item_insert
  ON public.tyapp_daily_log_template_item;
DROP POLICY IF EXISTS tyapp_daily_log_template_item_update
  ON public.tyapp_daily_log_template_item;

CREATE POLICY tyapp_daily_log_item_select
  ON public.tyapp_daily_log_item
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL);

CREATE POLICY tyapp_daily_log_item_insert
  ON public.tyapp_daily_log_item
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY tyapp_daily_log_item_update
  ON public.tyapp_daily_log_item
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL)
  WITH CHECK (user_id = auth.uid());

CREATE POLICY tyapp_daily_log_day_item_select
  ON public.tyapp_daily_log_day_item
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL);

CREATE POLICY tyapp_daily_log_day_item_insert
  ON public.tyapp_daily_log_day_item
  FOR INSERT
  TO authenticated
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.tyapp_daily_log_item i
      WHERE i.tb_tyapp_dl_itm_id = item_id
        AND i.user_id = auth.uid()
        AND i.deleted_at IS NULL
    )
  );

CREATE POLICY tyapp_daily_log_day_item_update
  ON public.tyapp_daily_log_day_item
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL)
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.tyapp_daily_log_item i
      WHERE i.tb_tyapp_dl_itm_id = item_id
        AND i.user_id = auth.uid()
        AND i.deleted_at IS NULL
    )
  );

CREATE POLICY tyapp_daily_log_template_item_select
  ON public.tyapp_daily_log_template_item
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL);

CREATE POLICY tyapp_daily_log_template_item_insert
  ON public.tyapp_daily_log_template_item
  FOR INSERT
  TO authenticated
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.tyapp_daily_log_item i
      WHERE i.tb_tyapp_dl_itm_id = item_id
        AND i.user_id = auth.uid()
        AND i.deleted_at IS NULL
    )
  );

CREATE POLICY tyapp_daily_log_template_item_update
  ON public.tyapp_daily_log_template_item
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL)
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.tyapp_daily_log_item i
      WHERE i.tb_tyapp_dl_itm_id = item_id
        AND i.user_id = auth.uid()
        AND i.deleted_at IS NULL
    )
  );

-- ---------------------------------------------------------------------------
-- Soft-delete RPCs
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.tyapp_daily_log_item_soft_delete_single_record(
  record_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_found uuid;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT tb_tyapp_dl_itm_id
  INTO v_found
  FROM public.tyapp_daily_log_item
  WHERE tb_tyapp_dl_itm_id = record_id
    AND user_id = v_uid
    AND deleted_at IS NULL;

  IF v_found IS NULL THEN
    RAISE EXCEPTION 'Library item not found or inaccessible';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.tyapp_daily_log_day_item d
    WHERE d.item_id = record_id
      AND d.user_id = v_uid
      AND d.deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Cannot delete this item while it is still on a date.';
  END IF;

  UPDATE public.tyapp_daily_log_template_item
  SET deleted_at = now()
  WHERE item_id = record_id
    AND user_id = v_uid
    AND deleted_at IS NULL;

  UPDATE public.tyapp_daily_log_item
  SET deleted_at = now()
  WHERE tb_tyapp_dl_itm_id = record_id
    AND user_id = v_uid
    AND deleted_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.tyapp_daily_log_day_item_soft_delete_single_record(
  record_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_found uuid;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT tb_tyapp_dl_day_id
  INTO v_found
  FROM public.tyapp_daily_log_day_item
  WHERE tb_tyapp_dl_day_id = record_id
    AND user_id = v_uid
    AND deleted_at IS NULL;

  IF v_found IS NULL THEN
    RAISE EXCEPTION 'Day item not found or inaccessible';
  END IF;

  UPDATE public.tyapp_daily_log_day_item
  SET deleted_at = now()
  WHERE tb_tyapp_dl_day_id = record_id
    AND user_id = v_uid
    AND deleted_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.tyapp_daily_log_template_item_soft_delete_single_record(
  record_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_found uuid;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT tb_tyapp_dl_tpl_id
  INTO v_found
  FROM public.tyapp_daily_log_template_item
  WHERE tb_tyapp_dl_tpl_id = record_id
    AND user_id = v_uid
    AND deleted_at IS NULL;

  IF v_found IS NULL THEN
    RAISE EXCEPTION 'Template item not found or inaccessible';
  END IF;

  UPDATE public.tyapp_daily_log_template_item
  SET deleted_at = now()
  WHERE tb_tyapp_dl_tpl_id = record_id
    AND user_id = v_uid
    AND deleted_at IS NULL;
END;
$$;

GRANT EXECUTE ON FUNCTION public.tyapp_daily_log_item_soft_delete_single_record(uuid)
  TO authenticated;
GRANT EXECUTE ON FUNCTION public.tyapp_daily_log_day_item_soft_delete_single_record(uuid)
  TO authenticated;
GRANT EXECUTE ON FUNCTION public.tyapp_daily_log_template_item_soft_delete_single_record(uuid)
  TO authenticated;

-- ---------------------------------------------------------------------------
-- Batch-create RPCs (copy item_id only; skip IDs already on the date)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.tyapp_daily_log_copy_previous_day(
  target_date date
)
RETURNS SETOF public.tyapp_daily_log_day_item
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_source_date date;
  v_base integer;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF target_date IS NULL THEN
    RAISE EXCEPTION 'target_date is required';
  END IF;

  v_source_date := target_date - 1;

  IF NOT EXISTS (
    SELECT 1
    FROM public.tyapp_daily_log_day_item
    WHERE user_id = v_uid
      AND log_date = v_source_date
      AND deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Yesterday has no active items to copy.';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.tyapp_daily_log_day_item y
    WHERE y.user_id = v_uid
      AND y.log_date = v_source_date
      AND y.deleted_at IS NULL
      AND NOT EXISTS (
        SELECT 1
        FROM public.tyapp_daily_log_day_item d
        WHERE d.user_id = v_uid
          AND d.log_date = target_date
          AND d.item_id = y.item_id
          AND d.deleted_at IS NULL
      )
  ) THEN
    RAISE EXCEPTION 'All of yesterday''s items are already on this date.';
  END IF;

  SELECT COALESCE(MAX(sort_order), -1)
  INTO v_base
  FROM public.tyapp_daily_log_day_item
  WHERE user_id = v_uid
    AND log_date = target_date
    AND deleted_at IS NULL;

  RETURN QUERY
  WITH src AS (
    SELECT
      y.item_id,
      y.sort_order,
      y.tb_tyapp_dl_day_seq_no,
      row_number() OVER (
        ORDER BY y.sort_order ASC, y.tb_tyapp_dl_day_seq_no ASC
      ) AS rn
    FROM public.tyapp_daily_log_day_item y
    WHERE y.user_id = v_uid
      AND y.log_date = v_source_date
      AND y.deleted_at IS NULL
      AND NOT EXISTS (
        SELECT 1
        FROM public.tyapp_daily_log_day_item d
        WHERE d.user_id = v_uid
          AND d.log_date = target_date
          AND d.item_id = y.item_id
          AND d.deleted_at IS NULL
      )
  ),
  ins AS (
    INSERT INTO public.tyapp_daily_log_day_item (
      user_id,
      item_id,
      log_date,
      sort_order,
      status,
      completed_at
    )
    SELECT
      v_uid,
      s.item_id,
      target_date,
      v_base + s.rn::integer,
      1,
      NULL
    FROM src s
    ORDER BY s.rn
    RETURNING *
  )
  SELECT *
  FROM ins
  ORDER BY sort_order ASC, tb_tyapp_dl_day_seq_no ASC;
END;
$$;

CREATE OR REPLACE FUNCTION public.tyapp_daily_log_create_from_template(
  target_date date
)
RETURNS SETOF public.tyapp_daily_log_day_item
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_base integer;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF target_date IS NULL THEN
    RAISE EXCEPTION 'target_date is required';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.tyapp_daily_log_template_item
    WHERE user_id = v_uid
      AND deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Your Standard Checklist is empty. Add items on the Standard Checklist page first.';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.tyapp_daily_log_template_item s
    WHERE s.user_id = v_uid
      AND s.deleted_at IS NULL
      AND NOT EXISTS (
        SELECT 1
        FROM public.tyapp_daily_log_day_item d
        WHERE d.user_id = v_uid
          AND d.log_date = target_date
          AND d.item_id = s.item_id
          AND d.deleted_at IS NULL
      )
  ) THEN
    RAISE EXCEPTION 'All standard items are already on this date.';
  END IF;

  SELECT COALESCE(MAX(sort_order), -1)
  INTO v_base
  FROM public.tyapp_daily_log_day_item
  WHERE user_id = v_uid
    AND log_date = target_date
    AND deleted_at IS NULL;

  RETURN QUERY
  WITH src AS (
    SELECT
      s.item_id,
      s.sort_order,
      s.tb_tyapp_dl_tpl_seq_no,
      row_number() OVER (
        ORDER BY s.sort_order ASC, s.tb_tyapp_dl_tpl_seq_no ASC
      ) AS rn
    FROM public.tyapp_daily_log_template_item s
    WHERE s.user_id = v_uid
      AND s.deleted_at IS NULL
      AND NOT EXISTS (
        SELECT 1
        FROM public.tyapp_daily_log_day_item d
        WHERE d.user_id = v_uid
          AND d.log_date = target_date
          AND d.item_id = s.item_id
          AND d.deleted_at IS NULL
      )
  ),
  ins AS (
    INSERT INTO public.tyapp_daily_log_day_item (
      user_id,
      item_id,
      log_date,
      sort_order,
      status,
      completed_at
    )
    SELECT
      v_uid,
      src.item_id,
      target_date,
      v_base + src.rn::integer,
      1,
      NULL
    FROM src
    ORDER BY src.rn
    RETURNING *
  )
  SELECT *
  FROM ins
  ORDER BY sort_order ASC, tb_tyapp_dl_day_seq_no ASC;
END;
$$;

GRANT EXECUTE ON FUNCTION public.tyapp_daily_log_copy_previous_day(date)
  TO authenticated;
GRANT EXECUTE ON FUNCTION public.tyapp_daily_log_create_from_template(date)
  TO authenticated;

-- ---------------------------------------------------------------------------
-- App Feature registry (no automatic user grants)
-- ---------------------------------------------------------------------------

INSERT INTO public.tyapp_app_feature (
  app_id,
  name,
  icon,
  route,
  remarks,
  status,
  show_in_launcher,
  is_admin_only,
  customized_order
)
SELECT
  (SELECT tb_tyapp_app_id FROM public.tyapp_app WHERE name = 'Jaxfr' AND deleted_at IS NULL LIMIT 1),
  'Daily Log',
  'checklist',
  '/daily-log',
  'Personal dated work log',
  1,
  true,
  false,
  (SELECT COALESCE(MAX(customized_order), 0) + 1 FROM public.tyapp_app_feature)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.tyapp_app_feature
  WHERE name = 'Daily Log'
    AND deleted_at IS NULL
);

UPDATE public.tyapp_app_feature
SET
  icon = 'checklist',
  route = '/daily-log',
  is_admin_only = false,
  show_in_launcher = true,
  status = 1,
  remarks = COALESCE(remarks, 'Personal dated work log'),
  updated_at = now()
WHERE name = 'Daily Log'
  AND deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_daily_log_day (
  tb_tyapp_dl_log_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_dl_log_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES auth.users (id),
  log_date date NOT NULL,
  mood_key text,
  title text,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_daily_log_day_mood_key
    CHECK (mood_key IS NULL OR mood_key IN (
      'green', 'gold', 'red', 'blue', 'purple',
      'grin', 'rest', 'blank', 'cry', 'mad'
    ))
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_daily_log_day_user_date_uniq
  ON public.tyapp_daily_log_day (user_id, log_date)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_daily_log_day_user_date_idx
  ON public.tyapp_daily_log_day (user_id, log_date)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS tyapp_daily_log_day_set_updated_at
  ON public.tyapp_daily_log_day;
CREATE TRIGGER tyapp_daily_log_day_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_daily_log_day
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.tyapp_daily_log_share (
  tb_tyapp_dl_shr_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_dl_shr_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  owner_user_id uuid NOT NULL REFERENCES auth.users (id),
  viewer_user_id uuid NOT NULL REFERENCES auth.users (id),
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_daily_log_share_not_self
    CHECK (owner_user_id <> viewer_user_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_daily_log_share_pair_uniq
  ON public.tyapp_daily_log_share (owner_user_id, viewer_user_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_daily_log_share_viewer_idx
  ON public.tyapp_daily_log_share (viewer_user_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS tyapp_daily_log_share_set_updated_at
  ON public.tyapp_daily_log_share;
CREATE TRIGGER tyapp_daily_log_share_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_daily_log_share
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.tyapp_daily_log_share_enforce_group()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.tyapp_user_ids_share_a_group(
    ARRAY[NEW.owner_user_id, NEW.viewer_user_id]
  ) THEN
    RAISE EXCEPTION 'Everyone granted access must belong to the same user group';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tyapp_daily_log_share_enforce_group
  ON public.tyapp_daily_log_share;
CREATE TRIGGER tyapp_daily_log_share_enforce_group
  BEFORE INSERT OR UPDATE OF owner_user_id, viewer_user_id
  ON public.tyapp_daily_log_share
  FOR EACH ROW
  EXECUTE FUNCTION public.tyapp_daily_log_share_enforce_group();

ALTER TABLE public.tyapp_daily_log_day ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_daily_log_day FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE ON public.tyapp_daily_log_day TO authenticated;

ALTER TABLE public.tyapp_daily_log_share ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_daily_log_share FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE ON public.tyapp_daily_log_share TO authenticated;

DROP POLICY IF EXISTS tyapp_daily_log_share_select
  ON public.tyapp_daily_log_share;
DROP POLICY IF EXISTS tyapp_daily_log_share_insert
  ON public.tyapp_daily_log_share;
DROP POLICY IF EXISTS tyapp_daily_log_share_update
  ON public.tyapp_daily_log_share;
DROP POLICY IF EXISTS tyapp_daily_log_day_select
  ON public.tyapp_daily_log_day;
DROP POLICY IF EXISTS tyapp_daily_log_day_insert
  ON public.tyapp_daily_log_day;
DROP POLICY IF EXISTS tyapp_daily_log_day_update
  ON public.tyapp_daily_log_day;

CREATE POLICY tyapp_daily_log_share_select
  ON public.tyapp_daily_log_share
  FOR SELECT
  TO authenticated
  USING (
    deleted_at IS NULL
    AND (owner_user_id = auth.uid() OR viewer_user_id = auth.uid())
  );

CREATE POLICY tyapp_daily_log_share_insert
  ON public.tyapp_daily_log_share
  FOR INSERT
  TO authenticated
  WITH CHECK (owner_user_id = auth.uid());

CREATE POLICY tyapp_daily_log_share_update
  ON public.tyapp_daily_log_share
  FOR UPDATE
  TO authenticated
  USING (owner_user_id = auth.uid() AND deleted_at IS NULL)
  WITH CHECK (owner_user_id = auth.uid());

CREATE POLICY tyapp_daily_log_day_select
  ON public.tyapp_daily_log_day
  FOR SELECT
  TO authenticated
  USING (
    deleted_at IS NULL
    AND (
      user_id = auth.uid()
      OR EXISTS (
        SELECT 1
        FROM public.tyapp_daily_log_share s
        WHERE s.owner_user_id = user_id
          AND s.viewer_user_id = auth.uid()
          AND s.deleted_at IS NULL
      )
    )
  );

CREATE POLICY tyapp_daily_log_day_insert
  ON public.tyapp_daily_log_day
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY tyapp_daily_log_day_update
  ON public.tyapp_daily_log_day
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL)
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS tyapp_daily_log_item_select
  ON public.tyapp_daily_log_item;
DROP POLICY IF EXISTS tyapp_daily_log_day_item_select
  ON public.tyapp_daily_log_day_item;

CREATE POLICY tyapp_daily_log_item_select
  ON public.tyapp_daily_log_item
  FOR SELECT
  TO authenticated
  USING (
    deleted_at IS NULL
    AND (
      user_id = auth.uid()
      OR EXISTS (
        SELECT 1
        FROM public.tyapp_daily_log_share s
        WHERE s.owner_user_id = user_id
          AND s.viewer_user_id = auth.uid()
          AND s.deleted_at IS NULL
      )
    )
  );

CREATE POLICY tyapp_daily_log_day_item_select
  ON public.tyapp_daily_log_day_item
  FOR SELECT
  TO authenticated
  USING (
    deleted_at IS NULL
    AND (
      user_id = auth.uid()
      OR EXISTS (
        SELECT 1
        FROM public.tyapp_daily_log_share s
        WHERE s.owner_user_id = user_id
          AND s.viewer_user_id = auth.uid()
          AND s.deleted_at IS NULL
      )
    )
  );

CREATE OR REPLACE FUNCTION public.tyapp_daily_log_share_soft_delete_single_record(
  record_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_found uuid;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT tb_tyapp_dl_shr_id
  INTO v_found
  FROM public.tyapp_daily_log_share
  WHERE tb_tyapp_dl_shr_id = record_id
    AND owner_user_id = v_uid
    AND deleted_at IS NULL;

  IF v_found IS NULL THEN
    RAISE EXCEPTION 'Share grant not found or inaccessible';
  END IF;

  UPDATE public.tyapp_daily_log_share
  SET deleted_at = now()
  WHERE tb_tyapp_dl_shr_id = record_id
    AND owner_user_id = v_uid
    AND deleted_at IS NULL;
END;
$$;

GRANT EXECUTE ON FUNCTION public.tyapp_daily_log_share_soft_delete_single_record(uuid)
  TO authenticated;

NOTIFY pgrst, 'reload schema';
