-- ============================================================================
-- Migration: App / Feature registry + per-user access control
-- Paste this entire file into the Supabase SQL editor and run top to bottom.
-- Every statement is safe to re-run (idempotent).
--
-- What this does:
--   1. Creates tyapp_app (App registry: Jaxfr / Filelink / Share)
--   2. Renames tyapp_app_category -> tyapp_app_feature and restructures it
--      (drops name_en/name_zh, renames display_name -> name, adds app_id /
--      icon / route / is_admin_only / show_in_launcher)
--   3. Reclassifies the existing rows (which ones are real launcher features
--      vs. legacy/log-only tags) using the real tb_tyapp_ap_ctgy_id values
--      from production
--   4. Renames tyapp_app_log.category_id -> feature_id
--   5. Creates tyapp_user_feature_access + tyapp_user_app_access (grant
--      tables) and migrates tyapp_user.allowed_apps into the latter
--   6. Backfills initial grants so no current user loses access to anything
--      they can already see today
--
-- NOT done here (deliberately): tyapp_user.allowed_apps is NOT dropped yet.
-- The Angular code (guards, login flow) still reads it. We'll drop it in a
-- later patch once that code is migrated to read tyapp_user_app_access.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 0. Shared helper (defensive re-create; already exists from
--    app-settings.schema.sql / user-push.schema.sql)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- 1. tyapp_app (App registry)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.tyapp_app (
  tb_tyapp_app_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_app_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  remarks text,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_app_name_unique UNIQUE (name)
);

DROP TRIGGER IF EXISTS tyapp_app_set_updated_at ON public.tyapp_app;
CREATE TRIGGER tyapp_app_set_updated_at
  BEFORE UPDATE ON public.tyapp_app
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

INSERT INTO public.tyapp_app (name)
SELECT v.name
FROM (VALUES ('Jaxfr'), ('Filelink'), ('Share')) AS v(name)
WHERE NOT EXISTS (
  SELECT 1 FROM public.tyapp_app a WHERE a.name = v.name
);

ALTER TABLE public.tyapp_app ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_app FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE ON public.tyapp_app TO authenticated;

DROP POLICY IF EXISTS tyapp_app_select ON public.tyapp_app;
CREATE POLICY tyapp_app_select
  ON public.tyapp_app
  FOR SELECT
  TO authenticated
  USING (deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_app_write ON public.tyapp_app;
CREATE POLICY tyapp_app_write
  ON public.tyapp_app
  FOR ALL
  TO authenticated
  USING (public.tyapp_is_admin())
  WITH CHECK (public.tyapp_is_admin());

-- ---------------------------------------------------------------------------
-- 2. tyapp_app_category -> tyapp_app_feature
-- ---------------------------------------------------------------------------

ALTER TABLE IF EXISTS public.tyapp_app_category RENAME TO tyapp_app_feature;

ALTER TABLE public.tyapp_app_feature
  RENAME COLUMN tb_tyapp_ap_ctgy_id TO tb_tyapp_ap_ftr_id;
ALTER TABLE public.tyapp_app_feature
  RENAME COLUMN tb_tyapp_ap_ctgy_seq_no TO tb_tyapp_ap_ftr_seq_no;
ALTER TABLE public.tyapp_app_feature
  RENAME COLUMN display_name TO name;
ALTER TABLE public.tyapp_app_feature DROP COLUMN IF EXISTS name_en;
ALTER TABLE public.tyapp_app_feature DROP COLUMN IF EXISTS name_zh;

ALTER TABLE public.tyapp_app_feature
  ADD COLUMN IF NOT EXISTS app_id uuid REFERENCES public.tyapp_app (tb_tyapp_app_id),
  ADD COLUMN IF NOT EXISTS icon text,
  ADD COLUMN IF NOT EXISTS route text,
  ADD COLUMN IF NOT EXISTS is_admin_only boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS show_in_launcher boolean NOT NULL DEFAULT false;

-- Every existing row predates the App concept, so it's implicitly Jaxfr.
-- Alias `a` so `name` cannot bind to tyapp_app_feature.name.
UPDATE public.tyapp_app_feature AS f
SET app_id = a.tb_tyapp_app_id
FROM public.tyapp_app AS a
WHERE a.name = 'Jaxfr'
  AND f.app_id IS NULL;

ALTER TABLE public.tyapp_app_feature ALTER COLUMN app_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS tyapp_app_feature_app_idx
  ON public.tyapp_app_feature (app_id);

-- Guardrail: a launcher tile with no icon/route would silently render broken.
ALTER TABLE public.tyapp_app_feature
  DROP CONSTRAINT IF EXISTS tyapp_app_feature_launcher_requires_route_icon;
ALTER TABLE public.tyapp_app_feature
  ADD CONSTRAINT tyapp_app_feature_launcher_requires_route_icon
  CHECK (show_in_launcher = false OR (route IS NOT NULL AND icon IS NOT NULL));

-- ---------------------------------------------------------------------------
-- 3. Reclassify existing rows (real production IDs from tyapp_app_category)
-- ---------------------------------------------------------------------------

-- Real, navigable Jaxfr features -> show on the Welcome launcher.
UPDATE public.tyapp_app_feature SET
  name = 'Work', icon = 'work', route = '/work/attendance/list',
  is_admin_only = false, show_in_launcher = true
WHERE tb_tyapp_ap_ftr_id = 'c4507a7c-465e-49ff-9821-2d38bb814f9b';

UPDATE public.tyapp_app_feature SET
  name = 'Article', icon = 'article', route = '/article/feed',
  is_admin_only = false, show_in_launcher = true
WHERE tb_tyapp_ap_ftr_id = '00f69962-2ef7-48b8-97ee-499201688d42';

UPDATE public.tyapp_app_feature SET
  name = 'Fit', icon = 'fitness_center', route = '/fit/list',
  is_admin_only = false, show_in_launcher = true
WHERE tb_tyapp_ap_ftr_id = '66310ca1-0689-492a-8c69-aa00ca13655f';

UPDATE public.tyapp_app_feature SET
  name = 'Filelink', icon = 'link', route = '/filelink/list',
  is_admin_only = false, show_in_launcher = true
WHERE tb_tyapp_ap_ftr_id = 'f8dd8537-1f62-43c7-bd8c-f2dfd1edbdfb';

UPDATE public.tyapp_app_feature SET
  name = 'Chat', icon = 'chat', route = '/chat',
  is_admin_only = false, show_in_launcher = true
WHERE tb_tyapp_ap_ftr_id = '8dbd0344-abe6-4964-ac0d-fb3edc009975';

UPDATE public.tyapp_app_feature SET
  name = 'Settings', icon = 'settings', route = '/settings/notifications',
  is_admin_only = false, show_in_launcher = true
WHERE tb_tyapp_ap_ftr_id = 'c04a9560-05b1-4d57-a3c5-b88a40f8345d';

-- "TY Web App Logs" broadens into the whole Development area (it already
-- covers the only thing Development is used for today).
UPDATE public.tyapp_app_feature SET
  name = 'Development', icon = 'code', route = '/development/log/list',
  is_admin_only = true, show_in_launcher = true
WHERE tb_tyapp_ap_ftr_id = '1d202738-605f-4fca-b955-3433dbbdd7d4';

-- User Management never had a category at all.
INSERT INTO public.tyapp_app_feature (
  app_id, name, icon, route, is_admin_only, show_in_launcher
)
SELECT
  (SELECT tb_tyapp_app_id FROM public.tyapp_app WHERE name = 'Jaxfr'),
  'User', 'people_outline', '/users/list', true, true
WHERE NOT EXISTS (
  SELECT 1 FROM public.tyapp_app_feature WHERE name = 'User'
);

-- "Section: Share" / "Section: Filelink" were a workaround for tagging App
-- Log entries before Apps existed as their own concept. Move them under
-- their real App. Keep the original names — do not rename to a shared
-- "General" label (that made the list look like every feature was General).
UPDATE public.tyapp_app_feature SET
  app_id = (SELECT a.tb_tyapp_app_id FROM public.tyapp_app a WHERE a.name = 'Share'),
  show_in_launcher = false
WHERE tb_tyapp_ap_ftr_id = 'a3bb36cc-e72d-4f09-8053-1a951830cd02';

UPDATE public.tyapp_app_feature SET
  app_id = (SELECT a.tb_tyapp_app_id FROM public.tyapp_app a WHERE a.name = 'Filelink'),
  show_in_launcher = false
WHERE tb_tyapp_ap_ftr_id = 'efadeb51-bad8-49ef-952f-6ec27b8c3895';

-- Everything else (Tyweb, yy525, Wealth Management, Bill Management, and
-- every already-soft-deleted test row) stays app_id = Jaxfr,
-- show_in_launcher = false (the column default) — kept only so App Log's
-- historical entries still resolve a name, never shown on the launcher.

-- ---------------------------------------------------------------------------
-- 4. RPC rename (soft delete)
-- ---------------------------------------------------------------------------

DROP FUNCTION IF EXISTS public.tyapp_app_category_soft_delete_single_record(uuid);

CREATE OR REPLACE FUNCTION public.tyapp_app_feature_soft_delete_single_record(
  record_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.tyapp_is_admin() THEN
    RAISE EXCEPTION 'Only admins can delete features';
  END IF;

  UPDATE public.tyapp_app_feature
  SET deleted_at = now()
  WHERE tb_tyapp_ap_ftr_id = record_id
    AND deleted_at IS NULL;
END;
$$;

GRANT EXECUTE ON FUNCTION public.tyapp_app_feature_soft_delete_single_record(uuid)
  TO authenticated;

NOTIFY pgrst, 'reload schema';

-- ---------------------------------------------------------------------------
-- 5. RLS on tyapp_app_feature — drop ALL existing policies first (this table
--    used to be tyapp_app_category, created directly in Supabase Studio with
--    no committed schema file, so we don't know the old policy names).
-- ---------------------------------------------------------------------------

DO $$
DECLARE
  pol record;
BEGIN
  FOR pol IN
    SELECT policyname FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'tyapp_app_feature'
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.tyapp_app_feature', pol.policyname);
  END LOOP;
END $$;

ALTER TABLE public.tyapp_app_feature ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_app_feature FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE ON public.tyapp_app_feature TO authenticated;

CREATE POLICY tyapp_app_feature_select
  ON public.tyapp_app_feature
  FOR SELECT
  TO authenticated
  USING (deleted_at IS NULL);

CREATE POLICY tyapp_app_feature_write
  ON public.tyapp_app_feature
  FOR ALL
  TO authenticated
  USING (public.tyapp_is_admin())
  WITH CHECK (public.tyapp_is_admin());

-- ---------------------------------------------------------------------------
-- 6. tyapp_app_log: category_id -> feature_id
-- ---------------------------------------------------------------------------

ALTER TABLE public.tyapp_app_log RENAME COLUMN category_id TO feature_id;

-- ---------------------------------------------------------------------------
-- 7. tyapp_user_feature_access (grant table, no soft delete — revoke = delete row)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.tyapp_user_feature_access (
  tb_tyapp_usr_ftr_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.tyapp_user (user_id),
  feature_id uuid NOT NULL REFERENCES public.tyapp_app_feature (tb_tyapp_ap_ftr_id),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tyapp_user_feature_access_unique UNIQUE (user_id, feature_id)
);

CREATE INDEX IF NOT EXISTS tyapp_user_feature_access_user_idx
  ON public.tyapp_user_feature_access (user_id);

ALTER TABLE public.tyapp_user_feature_access ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_user_feature_access FROM PUBLIC, anon;
GRANT SELECT, INSERT, DELETE ON public.tyapp_user_feature_access TO authenticated;

DROP POLICY IF EXISTS tyapp_user_feature_access_select ON public.tyapp_user_feature_access;
CREATE POLICY tyapp_user_feature_access_select
  ON public.tyapp_user_feature_access
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid() OR public.tyapp_is_admin());

DROP POLICY IF EXISTS tyapp_user_feature_access_write ON public.tyapp_user_feature_access;
CREATE POLICY tyapp_user_feature_access_write
  ON public.tyapp_user_feature_access
  FOR ALL
  TO authenticated
  USING (public.tyapp_is_admin())
  WITH CHECK (public.tyapp_is_admin());

-- ---------------------------------------------------------------------------
-- 8. tyapp_user_app_access (grant table) + migrate allowed_apps
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.tyapp_user_app_access (
  tb_tyapp_usr_app_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.tyapp_user (user_id),
  app_id uuid NOT NULL REFERENCES public.tyapp_app (tb_tyapp_app_id),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tyapp_user_app_access_unique UNIQUE (user_id, app_id)
);

CREATE INDEX IF NOT EXISTS tyapp_user_app_access_user_idx
  ON public.tyapp_user_app_access (user_id);

ALTER TABLE public.tyapp_user_app_access ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_user_app_access FROM PUBLIC, anon;
GRANT SELECT, INSERT, DELETE ON public.tyapp_user_app_access TO authenticated;

DROP POLICY IF EXISTS tyapp_user_app_access_select ON public.tyapp_user_app_access;
CREATE POLICY tyapp_user_app_access_select
  ON public.tyapp_user_app_access
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid() OR public.tyapp_is_admin());

DROP POLICY IF EXISTS tyapp_user_app_access_write ON public.tyapp_user_app_access;
CREATE POLICY tyapp_user_app_access_write
  ON public.tyapp_user_app_access
  FOR ALL
  TO authenticated
  USING (public.tyapp_is_admin())
  WITH CHECK (public.tyapp_is_admin());

-- Migrate tyapp_user.allowed_apps (text[] like '{jaxfr,filelink}') into rows.
INSERT INTO public.tyapp_user_app_access (user_id, app_id)
SELECT u.user_id, a.tb_tyapp_app_id
FROM public.tyapp_user u
CROSS JOIN LATERAL unnest(u.allowed_apps) AS x(app_code)
INNER JOIN public.tyapp_app a
  ON lower(a.name) = lower(x.app_code)
WHERE u.deleted_at IS NULL
ON CONFLICT (user_id, app_id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 9. Initial feature-access backfill — keeps everyone's current visibility
--    unchanged so nobody loses access the moment this ships.
-- ---------------------------------------------------------------------------

-- Non-admin-only launcher features -> every active user (matches what
-- everyone can already see today via the sidebar).
INSERT INTO public.tyapp_user_feature_access (user_id, feature_id)
SELECT u.user_id, f.tb_tyapp_ap_ftr_id
FROM public.tyapp_user u
CROSS JOIN public.tyapp_app_feature f
WHERE u.deleted_at IS NULL
  AND f.deleted_at IS NULL
  AND f.show_in_launcher = true
  AND f.is_admin_only = false
ON CONFLICT (user_id, feature_id) DO NOTHING;

-- Admin-only launcher features -> only today's admins (role >= 900),
-- matching current adminGuard/isAdmin behaviour.
INSERT INTO public.tyapp_user_feature_access (user_id, feature_id)
SELECT u.user_id, f.tb_tyapp_ap_ftr_id
FROM public.tyapp_user u
CROSS JOIN public.tyapp_app_feature f
WHERE u.deleted_at IS NULL
  AND u.role >= 900
  AND f.deleted_at IS NULL
  AND f.show_in_launcher = true
  AND f.is_admin_only = true
ON CONFLICT (user_id, feature_id) DO NOTHING;
