-- Incremental patch for existing Jaxfr chat databases.
-- Paste into the Supabase SQL editor (do not re-run the full chat.schema.sql).
-- 1) Room rename RPC
-- 2) Let members SELECT soft-deleted rooms so Realtime can broadcast deletes
-- 3) App-wide tyapp_app_settings singleton; edit/delete windows live there
--    (drops the short-lived tyapp_chat_config if it was created)
-- 4) Allow longer emoji sequences (ZWJ / skin tones) in reactions
-- 5) Multi-quote: quote_message_id uuid → quote_message_ids uuid[]
-- 6) Room read watermarks (已讀 initials + unread counts)

CREATE OR REPLACE FUNCTION public.tyapp_chat_rename_room(
  p_room_id uuid,
  p_name text
)
RETURNS public.tyapp_chat_room
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.tyapp_chat_room;
  v_name text := trim(p_name);
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF v_name IS NULL OR length(v_name) = 0 THEN
    RAISE EXCEPTION 'Room name is required';
  END IF;

  IF NOT public.tyapp_chat_is_room_member(p_room_id) THEN
    RAISE EXCEPTION 'Not a room member';
  END IF;

  UPDATE public.tyapp_chat_room
  SET name = v_name
  WHERE tb_tyapp_chat_rm_id = p_room_id
    AND deleted_at IS NULL
  RETURNING * INTO v_row;

  IF v_row.tb_tyapp_chat_rm_id IS NULL THEN
    RAISE EXCEPTION 'Room not found';
  END IF;

  RETURN v_row;
END;
$$;

GRANT EXECUTE ON FUNCTION public.tyapp_chat_rename_room(uuid, text) TO authenticated;

-- Soft-deleted rooms must still pass SELECT so Realtime can deliver the
-- UPDATE (otherwise other members never see the room disappear).
-- The app continues to filter deleted_at IS NULL on fetch.
DROP POLICY IF EXISTS tyapp_chat_room_select ON public.tyapp_chat_room;
CREATE POLICY tyapp_chat_room_select
  ON public.tyapp_chat_room
  FOR SELECT
  TO authenticated
  USING (auth.uid() = ANY (member_user_ids));

-- Drop the short-lived chat-only config table if a previous draft created it.
DROP TABLE IF EXISTS public.tyapp_chat_config;

-- App-wide singleton settings (canonical copy also lives in
-- features/development/app-settings/app-settings.schema.sql).
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.tyapp_app_settings (
  tb_tyapp_app_stng_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_app_stng_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  singleton_key smallint NOT NULL DEFAULT 1,
  chat_edit_window_ms integer NOT NULL DEFAULT 300000
    CHECK (chat_edit_window_ms > 0),
  chat_delete_window_ms integer NOT NULL DEFAULT 300000
    CHECK (chat_delete_window_ms > 0),
  remarks text,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_app_settings_singleton_key_chk CHECK (singleton_key = 1)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tyapp_app_settings_singleton_active
  ON public.tyapp_app_settings (singleton_key)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS tyapp_app_settings_set_updated_at
  ON public.tyapp_app_settings;
CREATE TRIGGER tyapp_app_settings_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_app_settings
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

INSERT INTO public.tyapp_app_settings (
  singleton_key,
  chat_edit_window_ms,
  chat_delete_window_ms
)
SELECT 1, 300000, 300000
WHERE NOT EXISTS (
  SELECT 1
  FROM public.tyapp_app_settings
  WHERE singleton_key = 1
    AND deleted_at IS NULL
);

ALTER TABLE public.tyapp_app_settings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_app_settings FROM PUBLIC, anon;
GRANT SELECT ON public.tyapp_app_settings TO authenticated;

DROP POLICY IF EXISTS tyapp_app_settings_select ON public.tyapp_app_settings;
CREATE POLICY tyapp_app_settings_select
  ON public.tyapp_app_settings
  FOR SELECT
  TO authenticated
  USING (deleted_at IS NULL AND status = 1);

CREATE OR REPLACE FUNCTION public.tyapp_chat_edit_message(
  p_message_id uuid,
  p_body text,
  p_body_plain text
)
RETURNS public.tyapp_chat_message
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.tyapp_chat_message;
  v_edit_ms integer;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT *
  INTO v_row
  FROM public.tyapp_chat_message
  WHERE tb_tyapp_chat_msg_id = p_message_id
    AND deleted_at IS NULL;

  IF v_row.tb_tyapp_chat_msg_id IS NULL THEN
    RAISE EXCEPTION 'Message not found';
  END IF;

  IF v_row.sender_user_id IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'Only the original sender can edit';
  END IF;

  IF NOT public.tyapp_chat_is_room_member(v_row.room_id) THEN
    RAISE EXCEPTION 'Not a room member';
  END IF;

  SELECT chat_edit_window_ms
  INTO v_edit_ms
  FROM public.tyapp_app_settings
  WHERE singleton_key = 1
    AND deleted_at IS NULL
    AND status = 1;

  IF v_edit_ms IS NULL THEN
    RAISE EXCEPTION 'App settings are missing';
  END IF;

  IF now() > v_row.created_at + (v_edit_ms * interval '1 millisecond') THEN
    RAISE EXCEPTION 'Edit window has expired';
  END IF;

  UPDATE public.tyapp_chat_message
  SET
    body = COALESCE(p_body, ''),
    body_plain = COALESCE(p_body_plain, ''),
    edited_at = now()
  WHERE tb_tyapp_chat_msg_id = p_message_id
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$$;

CREATE OR REPLACE FUNCTION public.tyapp_chat_message_soft_delete_single_record(
  record_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_sender uuid;
  v_room_id uuid;
  v_created_at timestamptz;
  v_delete_ms integer;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT sender_user_id, room_id, created_at
  INTO v_sender, v_room_id, v_created_at
  FROM public.tyapp_chat_message
  WHERE tb_tyapp_chat_msg_id = record_id
    AND deleted_at IS NULL;

  IF v_room_id IS NULL THEN
    RAISE EXCEPTION 'Message not found';
  END IF;

  IF v_sender IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'Only the original sender can delete';
  END IF;

  IF NOT public.tyapp_chat_is_room_member(v_room_id) THEN
    RAISE EXCEPTION 'Not a room member';
  END IF;

  SELECT chat_delete_window_ms
  INTO v_delete_ms
  FROM public.tyapp_app_settings
  WHERE singleton_key = 1
    AND deleted_at IS NULL
    AND status = 1;

  IF v_delete_ms IS NULL THEN
    RAISE EXCEPTION 'App settings are missing';
  END IF;

  IF now() > v_created_at + (v_delete_ms * interval '1 millisecond') THEN
    RAISE EXCEPTION 'Delete window has expired';
  END IF;

  UPDATE public.tyapp_chat_message
  SET deleted_at = now()
  WHERE tb_tyapp_chat_msg_id = record_id
    AND deleted_at IS NULL;
END;
$$;

-- Allow ZWJ / skin-tone sequences from the full emoji picker (was 16).
CREATE OR REPLACE FUNCTION public.tyapp_chat_toggle_reaction(
  p_message_id uuid,
  p_emoji text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_room_id uuid;
  v_reactions jsonb;
  v_list jsonb;
  v_uid uuid := auth.uid();
  v_found boolean;
  v_new_list jsonb;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF p_emoji IS NULL OR length(trim(p_emoji)) = 0 OR length(p_emoji) > 64 THEN
    RAISE EXCEPTION 'Invalid emoji';
  END IF;

  SELECT room_id, reactions
  INTO v_room_id, v_reactions
  FROM public.tyapp_chat_message
  WHERE tb_tyapp_chat_msg_id = p_message_id
    AND deleted_at IS NULL;

  IF v_room_id IS NULL THEN
    RAISE EXCEPTION 'Message not found';
  END IF;

  IF NOT public.tyapp_chat_is_room_member(v_room_id) THEN
    RAISE EXCEPTION 'Not a room member';
  END IF;

  v_reactions := COALESCE(v_reactions, '{}'::jsonb);
  v_list := COALESCE(v_reactions -> p_emoji, '[]'::jsonb);

  SELECT EXISTS (
    SELECT 1
    FROM jsonb_array_elements(v_list) e
    WHERE e ->> 'user_id' = v_uid::text
  )
  INTO v_found;

  IF v_found THEN
    SELECT COALESCE(jsonb_agg(e), '[]'::jsonb)
    INTO v_new_list
    FROM jsonb_array_elements(v_list) e
    WHERE e ->> 'user_id' <> v_uid::text;
  ELSE
    v_new_list := v_list || jsonb_build_array(
      jsonb_build_object(
        'user_id', v_uid,
        'created_at', now()
      )
    );
  END IF;

  IF v_new_list = '[]'::jsonb THEN
    v_reactions := v_reactions - p_emoji;
  ELSE
    v_reactions := jsonb_set(v_reactions, ARRAY[p_emoji], v_new_list);
  END IF;

  UPDATE public.tyapp_chat_message
  SET reactions = v_reactions
  WHERE tb_tyapp_chat_msg_id = p_message_id;

  RETURN v_reactions;
END;
$$;

-- 5) Multi-quote: expand → backfill → drop. Idempotent.
--    Re-running after quote_message_id is gone skips the backfill/drop.
ALTER TABLE public.tyapp_chat_message
  ADD COLUMN IF NOT EXISTS quote_message_ids uuid[] NOT NULL DEFAULT '{}';

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'tyapp_chat_message'
      AND column_name = 'quote_message_id'
  ) THEN
    UPDATE public.tyapp_chat_message
    SET quote_message_ids = ARRAY[quote_message_id]
    WHERE quote_message_id IS NOT NULL
      AND cardinality(COALESCE(quote_message_ids, '{}'::uuid[])) = 0;

    ALTER TABLE public.tyapp_chat_message
      DROP COLUMN quote_message_id;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'tyapp_chat_message_quote_ids_max'
  ) THEN
    ALTER TABLE public.tyapp_chat_message
      ADD CONSTRAINT tyapp_chat_message_quote_ids_max
      CHECK (cardinality(quote_message_ids) <= 10);
  END IF;
END $$;

-- 6) Room read watermarks. Idempotent.
CREATE TABLE IF NOT EXISTS public.tyapp_chat_room_read (
  tb_tyapp_chat_rd_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_chat_rd_seq_no bigint GENERATED ALWAYS AS IDENTITY,
  room_id uuid NOT NULL REFERENCES public.tyapp_chat_room (tb_tyapp_chat_rm_id),
  user_id uuid NOT NULL REFERENCES public.tyapp_user (user_id),
  last_read_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tyapp_chat_room_read_unique UNIQUE (room_id, user_id)
);

CREATE INDEX IF NOT EXISTS tyapp_chat_room_read_room_idx
  ON public.tyapp_chat_room_read (room_id);

DROP TRIGGER IF EXISTS tyapp_chat_room_read_set_updated_at ON public.tyapp_chat_room_read;
CREATE TRIGGER tyapp_chat_room_read_set_updated_at
  BEFORE UPDATE ON public.tyapp_chat_room_read
  FOR EACH ROW
  EXECUTE FUNCTION public.tyapp_chat_set_updated_at();

CREATE OR REPLACE FUNCTION public.tyapp_chat_mark_room_read(p_room_id uuid)
RETURNS public.tyapp_chat_room_read
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.tyapp_chat_room_read;
  v_uid uuid := auth.uid();
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF NOT public.tyapp_chat_is_room_member(p_room_id) THEN
    RAISE EXCEPTION 'Not a room member';
  END IF;

  INSERT INTO public.tyapp_chat_room_read (room_id, user_id, last_read_at)
  VALUES (p_room_id, v_uid, now())
  ON CONFLICT (room_id, user_id)
  DO UPDATE SET
    last_read_at = GREATEST(
      public.tyapp_chat_room_read.last_read_at,
      EXCLUDED.last_read_at
    )
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$$;

CREATE OR REPLACE FUNCTION public.tyapp_chat_unread_counts()
RETURNS TABLE (room_id uuid, unread_count bigint)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT m.room_id, count(*)::bigint
  FROM public.tyapp_chat_message m
  INNER JOIN public.tyapp_chat_room r
    ON r.tb_tyapp_chat_rm_id = m.room_id
   AND r.deleted_at IS NULL
   AND auth.uid() = ANY (r.member_user_ids)
  LEFT JOIN public.tyapp_chat_room_read rd
    ON rd.room_id = m.room_id
   AND rd.user_id = auth.uid()
  WHERE m.deleted_at IS NULL
    AND m.sender_user_id IS DISTINCT FROM auth.uid()
    AND (rd.last_read_at IS NULL OR m.created_at > rd.last_read_at)
  GROUP BY m.room_id;
$$;

ALTER TABLE public.tyapp_chat_room_read ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_chat_room_read FROM PUBLIC, anon;
GRANT SELECT ON public.tyapp_chat_room_read TO authenticated;
GRANT EXECUTE ON FUNCTION public.tyapp_chat_mark_room_read(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tyapp_chat_unread_counts() TO authenticated;

DROP POLICY IF EXISTS tyapp_chat_room_read_select ON public.tyapp_chat_room_read;
CREATE POLICY tyapp_chat_room_read_select
  ON public.tyapp_chat_room_read
  FOR SELECT
  TO authenticated
  USING (public.tyapp_chat_is_room_member(room_id));

ALTER TABLE public.tyapp_chat_room_read REPLICA IDENTITY FULL;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.tyapp_chat_room_read;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
