-- Jaxfr Daily Checklist schema, RLS, RPCs, and launcher registry row.
-- Paste this entire file into the Supabase SQL Editor and run top to bottom.
-- Safe to re-run (idempotent). Does not grant the feature to any user.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.tyapp_daily_checklist_item (
  tb_tyapp_dcl_itm_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_dcl_itm_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES auth.users (id),
  checklist_date date NOT NULL,
  item_text text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  completed_at timestamptz,
  remarks text,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_daily_checklist_item_text_not_blank
    CHECK (length(btrim(item_text)) > 0),
  CONSTRAINT tyapp_daily_checklist_item_sort_order_nonneg
    CHECK (sort_order >= 0)
);

CREATE TABLE IF NOT EXISTS public.tyapp_daily_checklist_template_item (
  tb_tyapp_dcl_tpl_itm_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_dcl_tpl_itm_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES auth.users (id),
  item_text text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  remarks text,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_daily_checklist_template_item_text_not_blank
    CHECK (length(btrim(item_text)) > 0),
  CONSTRAINT tyapp_daily_checklist_template_item_sort_order_nonneg
    CHECK (sort_order >= 0)
);

CREATE INDEX IF NOT EXISTS tyapp_daily_checklist_item_user_date_sort_idx
  ON public.tyapp_daily_checklist_item (user_id, checklist_date, sort_order)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_daily_checklist_item_user_completed_idx
  ON public.tyapp_daily_checklist_item (user_id, completed_at)
  WHERE deleted_at IS NULL AND completed_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS tyapp_daily_checklist_template_item_user_sort_idx
  ON public.tyapp_daily_checklist_template_item (user_id, sort_order)
  WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- updated_at triggers (shared public.set_updated_at())
-- ---------------------------------------------------------------------------

DROP TRIGGER IF EXISTS tyapp_daily_checklist_item_set_updated_at
  ON public.tyapp_daily_checklist_item;
CREATE TRIGGER tyapp_daily_checklist_item_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_daily_checklist_item
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_daily_checklist_template_item_set_updated_at
  ON public.tyapp_daily_checklist_template_item;
CREATE TRIGGER tyapp_daily_checklist_template_item_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_daily_checklist_template_item
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.tyapp_daily_checklist_item ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_daily_checklist_item FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE ON public.tyapp_daily_checklist_item TO authenticated;

ALTER TABLE public.tyapp_daily_checklist_template_item ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_daily_checklist_template_item FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE ON public.tyapp_daily_checklist_template_item TO authenticated;

DROP POLICY IF EXISTS tyapp_daily_checklist_item_select
  ON public.tyapp_daily_checklist_item;
CREATE POLICY tyapp_daily_checklist_item_select
  ON public.tyapp_daily_checklist_item
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_daily_checklist_item_insert
  ON public.tyapp_daily_checklist_item;
CREATE POLICY tyapp_daily_checklist_item_insert
  ON public.tyapp_daily_checklist_item
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS tyapp_daily_checklist_item_update
  ON public.tyapp_daily_checklist_item;
CREATE POLICY tyapp_daily_checklist_item_update
  ON public.tyapp_daily_checklist_item
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL)
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS tyapp_daily_checklist_template_item_select
  ON public.tyapp_daily_checklist_template_item;
CREATE POLICY tyapp_daily_checklist_template_item_select
  ON public.tyapp_daily_checklist_template_item
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_daily_checklist_template_item_insert
  ON public.tyapp_daily_checklist_template_item;
CREATE POLICY tyapp_daily_checklist_template_item_insert
  ON public.tyapp_daily_checklist_template_item
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS tyapp_daily_checklist_template_item_update
  ON public.tyapp_daily_checklist_template_item;
CREATE POLICY tyapp_daily_checklist_template_item_update
  ON public.tyapp_daily_checklist_template_item
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL)
  WITH CHECK (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Soft-delete RPCs
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.tyapp_daily_checklist_item_soft_delete_single_record(
  record_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_found uuid;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT tb_tyapp_dcl_itm_id
  INTO v_found
  FROM public.tyapp_daily_checklist_item
  WHERE tb_tyapp_dcl_itm_id = record_id
    AND user_id = v_uid
    AND deleted_at IS NULL;

  IF v_found IS NULL THEN
    RAISE EXCEPTION 'Checklist item not found or inaccessible';
  END IF;

  UPDATE public.tyapp_daily_checklist_item
  SET deleted_at = now()
  WHERE tb_tyapp_dcl_itm_id = record_id
    AND user_id = v_uid
    AND deleted_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.tyapp_daily_checklist_template_item_soft_delete_single_record(
  record_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_found uuid;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT tb_tyapp_dcl_tpl_itm_id
  INTO v_found
  FROM public.tyapp_daily_checklist_template_item
  WHERE tb_tyapp_dcl_tpl_itm_id = record_id
    AND user_id = v_uid
    AND deleted_at IS NULL;

  IF v_found IS NULL THEN
    RAISE EXCEPTION 'Standard checklist item not found or inaccessible';
  END IF;

  UPDATE public.tyapp_daily_checklist_template_item
  SET deleted_at = now()
  WHERE tb_tyapp_dcl_tpl_itm_id = record_id
    AND user_id = v_uid
    AND deleted_at IS NULL;
END;
$$;

GRANT EXECUTE ON FUNCTION public.tyapp_daily_checklist_item_soft_delete_single_record(uuid)
  TO authenticated;
GRANT EXECUTE ON FUNCTION public.tyapp_daily_checklist_template_item_soft_delete_single_record(uuid)
  TO authenticated;

-- ---------------------------------------------------------------------------
-- Atomic batch-create RPCs
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.tyapp_daily_checklist_create_from_template(
  target_date date
)
RETURNS SETOF public.tyapp_daily_checklist_item
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF target_date IS NULL THEN
    RAISE EXCEPTION 'target_date is required';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.tyapp_daily_checklist_item
    WHERE user_id = v_uid
      AND checklist_date = target_date
      AND deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'This date already has a checklist. Use standard checklist is only available on an empty date.';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.tyapp_daily_checklist_template_item
    WHERE user_id = v_uid
      AND deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Your Standard Checklist is empty. Add items on the Standard Checklist page first.';
  END IF;

  RETURN QUERY
  WITH src AS (
    SELECT
      t.item_text,
      t.remarks,
      t.sort_order,
      t.tb_tyapp_dcl_tpl_itm_seq_no
    FROM public.tyapp_daily_checklist_template_item t
    WHERE t.user_id = v_uid
      AND t.deleted_at IS NULL
    ORDER BY t.sort_order ASC, t.tb_tyapp_dcl_tpl_itm_seq_no ASC
  ),
  ins AS (
    INSERT INTO public.tyapp_daily_checklist_item (
      user_id,
      checklist_date,
      item_text,
      remarks,
      sort_order,
      status,
      completed_at
    )
    SELECT
      v_uid,
      target_date,
      s.item_text,
      s.remarks,
      s.sort_order,
      1,
      NULL
    FROM src s
    ORDER BY s.sort_order ASC, s.tb_tyapp_dcl_tpl_itm_seq_no ASC
    RETURNING *
  )
  SELECT *
  FROM ins
  ORDER BY sort_order ASC, tb_tyapp_dcl_itm_seq_no ASC;
END;
$$;

CREATE OR REPLACE FUNCTION public.tyapp_daily_checklist_copy_previous_day(
  target_date date
)
RETURNS SETOF public.tyapp_daily_checklist_item
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_source_date date;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF target_date IS NULL THEN
    RAISE EXCEPTION 'target_date is required';
  END IF;

  v_source_date := target_date - 1;

  IF EXISTS (
    SELECT 1
    FROM public.tyapp_daily_checklist_item
    WHERE user_id = v_uid
      AND checklist_date = target_date
      AND deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'This date already has a checklist. Copy yesterday is only available on an empty date.';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.tyapp_daily_checklist_item
    WHERE user_id = v_uid
      AND checklist_date = v_source_date
      AND deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Yesterday has no active checklist items to copy.';
  END IF;

  RETURN QUERY
  WITH src AS (
    SELECT
      i.item_text,
      i.remarks,
      i.sort_order,
      i.tb_tyapp_dcl_itm_seq_no
    FROM public.tyapp_daily_checklist_item i
    WHERE i.user_id = v_uid
      AND i.checklist_date = v_source_date
      AND i.deleted_at IS NULL
    ORDER BY i.sort_order ASC, i.tb_tyapp_dcl_itm_seq_no ASC
  ),
  ins AS (
    INSERT INTO public.tyapp_daily_checklist_item (
      user_id,
      checklist_date,
      item_text,
      remarks,
      sort_order,
      status,
      completed_at
    )
    SELECT
      v_uid,
      target_date,
      s.item_text,
      s.remarks,
      s.sort_order,
      1,
      NULL
    FROM src s
    ORDER BY s.sort_order ASC, s.tb_tyapp_dcl_itm_seq_no ASC
    RETURNING *
  )
  SELECT *
  FROM ins
  ORDER BY sort_order ASC, tb_tyapp_dcl_itm_seq_no ASC;
END;
$$;

GRANT EXECUTE ON FUNCTION public.tyapp_daily_checklist_create_from_template(date)
  TO authenticated;
GRANT EXECUTE ON FUNCTION public.tyapp_daily_checklist_copy_previous_day(date)
  TO authenticated;

-- ---------------------------------------------------------------------------
-- App Feature registry (no automatic user grants)
-- ---------------------------------------------------------------------------

INSERT INTO public.tyapp_app_feature (
  app_id,
  name,
  icon,
  route,
  remarks,
  status,
  show_in_launcher,
  is_admin_only,
  customized_order
)
SELECT
  (SELECT tb_tyapp_app_id FROM public.tyapp_app WHERE name = 'Jaxfr' AND deleted_at IS NULL LIMIT 1),
  'Daily Checklist',
  'checklist',
  '/daily-checklist',
  'Personal dated work checklist',
  1,
  true,
  false,
  (SELECT COALESCE(MAX(customized_order), 0) + 1 FROM public.tyapp_app_feature)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.tyapp_app_feature
  WHERE name = 'Daily Checklist'
    AND deleted_at IS NULL
);

UPDATE public.tyapp_app_feature
SET
  icon = 'checklist',
  route = '/daily-checklist',
  is_admin_only = false,
  show_in_launcher = true,
  status = 1,
  remarks = COALESCE(remarks, 'Personal dated work checklist'),
  updated_at = now()
WHERE name = 'Daily Checklist'
  AND deleted_at IS NULL;

NOTIFY pgrst, 'reload schema';
