-- Jaxfr Daily Checklist schema, RLS, and RPCs.
-- Paste this entire file into the Supabase SQL Editor and run top to bottom.
-- Safe to re-run: drops v1 tables/RPCs and recreates the three current tables.
-- Existing Daily Checklist rows are deleted. The App Feature registry row is kept.

-- ---------------------------------------------------------------------------
-- Reset (v1 names + current names)
-- ---------------------------------------------------------------------------

DROP FUNCTION IF EXISTS public.tyapp_daily_checklist_create_from_template(date);
DROP FUNCTION IF EXISTS public.tyapp_daily_checklist_create_from_standard(date);
DROP FUNCTION IF EXISTS public.tyapp_daily_checklist_copy_previous_day(date);
DROP FUNCTION IF EXISTS public.tyapp_daily_checklist_item_soft_delete_single_record(uuid);
DROP FUNCTION IF EXISTS public.tyapp_daily_checklist_template_item_soft_delete_single_record(uuid);
DROP FUNCTION IF EXISTS public.tyapp_daily_checklist_day_item_soft_delete_single_record(uuid);
DROP FUNCTION IF EXISTS public.tyapp_daily_checklist_standard_item_soft_delete_single_record(uuid);

DROP TABLE IF EXISTS public.tyapp_daily_checklist_day_item CASCADE;
DROP TABLE IF EXISTS public.tyapp_daily_checklist_standard_item CASCADE;
DROP TABLE IF EXISTS public.tyapp_daily_checklist_template_item CASCADE;
DROP TABLE IF EXISTS public.tyapp_daily_checklist_item CASCADE;

-- ---------------------------------------------------------------------------
-- Catalog: reusable item (name, emoji, colour)
-- ---------------------------------------------------------------------------

CREATE TABLE public.tyapp_daily_checklist_item (
  tb_tyapp_dcl_itm_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_dcl_itm_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES auth.users (id),
  item_text text NOT NULL,
  emoji text,
  colour_preset_key text NOT NULL DEFAULT 'slate',
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_daily_checklist_item_text_not_blank
    CHECK (length(btrim(item_text)) > 0),
  CONSTRAINT tyapp_daily_checklist_item_emoji_len
    CHECK (emoji IS NULL OR length(btrim(emoji)) BETWEEN 1 AND 32),
  CONSTRAINT tyapp_daily_checklist_item_colour_preset
    CHECK (colour_preset_key IN (
      'purple', 'blue', 'teal', 'green', 'gold', 'orange', 'red', 'slate'
    ))
);

CREATE UNIQUE INDEX tyapp_daily_checklist_item_user_name_uniq
  ON public.tyapp_daily_checklist_item (user_id, lower(btrim(item_text)))
  WHERE deleted_at IS NULL;

CREATE INDEX tyapp_daily_checklist_item_user_idx
  ON public.tyapp_daily_checklist_item (user_id)
  WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- Day occurrence: one catalog item on one date
-- ---------------------------------------------------------------------------

CREATE TABLE public.tyapp_daily_checklist_day_item (
  tb_tyapp_dcl_day_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_dcl_day_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES auth.users (id),
  item_id uuid NOT NULL REFERENCES public.tyapp_daily_checklist_item (tb_tyapp_dcl_itm_id),
  checklist_date date NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  completed_at timestamptz,
  remarks text,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_daily_checklist_day_item_sort_order_nonneg
    CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX tyapp_daily_checklist_day_item_user_date_item_uniq
  ON public.tyapp_daily_checklist_day_item (user_id, checklist_date, item_id)
  WHERE deleted_at IS NULL;

CREATE INDEX tyapp_daily_checklist_day_item_user_date_sort_idx
  ON public.tyapp_daily_checklist_day_item (user_id, checklist_date, sort_order)
  WHERE deleted_at IS NULL;

CREATE INDEX tyapp_daily_checklist_day_item_user_completed_idx
  ON public.tyapp_daily_checklist_day_item (user_id, completed_at)
  WHERE deleted_at IS NULL AND completed_at IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Standard pack: ordered catalog membership
-- ---------------------------------------------------------------------------

CREATE TABLE public.tyapp_daily_checklist_standard_item (
  tb_tyapp_dcl_std_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_dcl_std_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES auth.users (id),
  item_id uuid NOT NULL REFERENCES public.tyapp_daily_checklist_item (tb_tyapp_dcl_itm_id),
  sort_order integer NOT NULL DEFAULT 0,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_daily_checklist_standard_item_sort_order_nonneg
    CHECK (sort_order >= 0)
);

CREATE UNIQUE INDEX tyapp_daily_checklist_standard_item_user_item_uniq
  ON public.tyapp_daily_checklist_standard_item (user_id, item_id)
  WHERE deleted_at IS NULL;

CREATE INDEX tyapp_daily_checklist_standard_item_user_sort_idx
  ON public.tyapp_daily_checklist_standard_item (user_id, sort_order)
  WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- updated_at
-- ---------------------------------------------------------------------------

DROP TRIGGER IF EXISTS tyapp_daily_checklist_item_set_updated_at
  ON public.tyapp_daily_checklist_item;
CREATE TRIGGER tyapp_daily_checklist_item_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_daily_checklist_item
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_daily_checklist_day_item_set_updated_at
  ON public.tyapp_daily_checklist_day_item;
CREATE TRIGGER tyapp_daily_checklist_day_item_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_daily_checklist_day_item
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_daily_checklist_standard_item_set_updated_at
  ON public.tyapp_daily_checklist_standard_item;
CREATE TRIGGER tyapp_daily_checklist_standard_item_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_daily_checklist_standard_item
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.tyapp_daily_checklist_item ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_daily_checklist_item FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE ON public.tyapp_daily_checklist_item TO authenticated;

ALTER TABLE public.tyapp_daily_checklist_day_item ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_daily_checklist_day_item FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE ON public.tyapp_daily_checklist_day_item TO authenticated;

ALTER TABLE public.tyapp_daily_checklist_standard_item ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_daily_checklist_standard_item FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE ON public.tyapp_daily_checklist_standard_item TO authenticated;

DROP POLICY IF EXISTS tyapp_daily_checklist_item_select
  ON public.tyapp_daily_checklist_item;
DROP POLICY IF EXISTS tyapp_daily_checklist_item_insert
  ON public.tyapp_daily_checklist_item;
DROP POLICY IF EXISTS tyapp_daily_checklist_item_update
  ON public.tyapp_daily_checklist_item;
DROP POLICY IF EXISTS tyapp_daily_checklist_day_item_select
  ON public.tyapp_daily_checklist_day_item;
DROP POLICY IF EXISTS tyapp_daily_checklist_day_item_insert
  ON public.tyapp_daily_checklist_day_item;
DROP POLICY IF EXISTS tyapp_daily_checklist_day_item_update
  ON public.tyapp_daily_checklist_day_item;
DROP POLICY IF EXISTS tyapp_daily_checklist_standard_item_select
  ON public.tyapp_daily_checklist_standard_item;
DROP POLICY IF EXISTS tyapp_daily_checklist_standard_item_insert
  ON public.tyapp_daily_checklist_standard_item;
DROP POLICY IF EXISTS tyapp_daily_checklist_standard_item_update
  ON public.tyapp_daily_checklist_standard_item;

CREATE POLICY tyapp_daily_checklist_item_select
  ON public.tyapp_daily_checklist_item
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL);

CREATE POLICY tyapp_daily_checklist_item_insert
  ON public.tyapp_daily_checklist_item
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY tyapp_daily_checklist_item_update
  ON public.tyapp_daily_checklist_item
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL)
  WITH CHECK (user_id = auth.uid());

CREATE POLICY tyapp_daily_checklist_day_item_select
  ON public.tyapp_daily_checklist_day_item
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL);

CREATE POLICY tyapp_daily_checklist_day_item_insert
  ON public.tyapp_daily_checklist_day_item
  FOR INSERT
  TO authenticated
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.tyapp_daily_checklist_item i
      WHERE i.tb_tyapp_dcl_itm_id = item_id
        AND i.user_id = auth.uid()
        AND i.deleted_at IS NULL
    )
  );

CREATE POLICY tyapp_daily_checklist_day_item_update
  ON public.tyapp_daily_checklist_day_item
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL)
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.tyapp_daily_checklist_item i
      WHERE i.tb_tyapp_dcl_itm_id = item_id
        AND i.user_id = auth.uid()
        AND i.deleted_at IS NULL
    )
  );

CREATE POLICY tyapp_daily_checklist_standard_item_select
  ON public.tyapp_daily_checklist_standard_item
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL);

CREATE POLICY tyapp_daily_checklist_standard_item_insert
  ON public.tyapp_daily_checklist_standard_item
  FOR INSERT
  TO authenticated
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.tyapp_daily_checklist_item i
      WHERE i.tb_tyapp_dcl_itm_id = item_id
        AND i.user_id = auth.uid()
        AND i.deleted_at IS NULL
    )
  );

CREATE POLICY tyapp_daily_checklist_standard_item_update
  ON public.tyapp_daily_checklist_standard_item
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL)
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.tyapp_daily_checklist_item i
      WHERE i.tb_tyapp_dcl_itm_id = item_id
        AND i.user_id = auth.uid()
        AND i.deleted_at IS NULL
    )
  );

-- ---------------------------------------------------------------------------
-- Soft-delete RPCs
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.tyapp_daily_checklist_item_soft_delete_single_record(
  record_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_found uuid;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT tb_tyapp_dcl_itm_id
  INTO v_found
  FROM public.tyapp_daily_checklist_item
  WHERE tb_tyapp_dcl_itm_id = record_id
    AND user_id = v_uid
    AND deleted_at IS NULL;

  IF v_found IS NULL THEN
    RAISE EXCEPTION 'Checklist item not found or inaccessible';
  END IF;

  UPDATE public.tyapp_daily_checklist_item
  SET deleted_at = now()
  WHERE tb_tyapp_dcl_itm_id = record_id
    AND user_id = v_uid
    AND deleted_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.tyapp_daily_checklist_day_item_soft_delete_single_record(
  record_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_found uuid;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT tb_tyapp_dcl_day_id
  INTO v_found
  FROM public.tyapp_daily_checklist_day_item
  WHERE tb_tyapp_dcl_day_id = record_id
    AND user_id = v_uid
    AND deleted_at IS NULL;

  IF v_found IS NULL THEN
    RAISE EXCEPTION 'Day checklist item not found or inaccessible';
  END IF;

  UPDATE public.tyapp_daily_checklist_day_item
  SET deleted_at = now()
  WHERE tb_tyapp_dcl_day_id = record_id
    AND user_id = v_uid
    AND deleted_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.tyapp_daily_checklist_standard_item_soft_delete_single_record(
  record_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_found uuid;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT tb_tyapp_dcl_std_id
  INTO v_found
  FROM public.tyapp_daily_checklist_standard_item
  WHERE tb_tyapp_dcl_std_id = record_id
    AND user_id = v_uid
    AND deleted_at IS NULL;

  IF v_found IS NULL THEN
    RAISE EXCEPTION 'Standard checklist item not found or inaccessible';
  END IF;

  UPDATE public.tyapp_daily_checklist_standard_item
  SET deleted_at = now()
  WHERE tb_tyapp_dcl_std_id = record_id
    AND user_id = v_uid
    AND deleted_at IS NULL;
END;
$$;

GRANT EXECUTE ON FUNCTION public.tyapp_daily_checklist_item_soft_delete_single_record(uuid)
  TO authenticated;
GRANT EXECUTE ON FUNCTION public.tyapp_daily_checklist_day_item_soft_delete_single_record(uuid)
  TO authenticated;
GRANT EXECUTE ON FUNCTION public.tyapp_daily_checklist_standard_item_soft_delete_single_record(uuid)
  TO authenticated;

-- ---------------------------------------------------------------------------
-- Batch-create RPCs (copy item_id only; skip IDs already on the date)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.tyapp_daily_checklist_copy_previous_day(
  target_date date
)
RETURNS SETOF public.tyapp_daily_checklist_day_item
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_source_date date;
  v_base integer;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF target_date IS NULL THEN
    RAISE EXCEPTION 'target_date is required';
  END IF;

  v_source_date := target_date - 1;

  IF NOT EXISTS (
    SELECT 1
    FROM public.tyapp_daily_checklist_day_item
    WHERE user_id = v_uid
      AND checklist_date = v_source_date
      AND deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Yesterday has no active checklist items to copy.';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.tyapp_daily_checklist_day_item y
    WHERE y.user_id = v_uid
      AND y.checklist_date = v_source_date
      AND y.deleted_at IS NULL
      AND NOT EXISTS (
        SELECT 1
        FROM public.tyapp_daily_checklist_day_item d
        WHERE d.user_id = v_uid
          AND d.checklist_date = target_date
          AND d.item_id = y.item_id
          AND d.deleted_at IS NULL
      )
  ) THEN
    RAISE EXCEPTION 'All of yesterday''s items are already on this date.';
  END IF;

  SELECT COALESCE(MAX(sort_order), -1)
  INTO v_base
  FROM public.tyapp_daily_checklist_day_item
  WHERE user_id = v_uid
    AND checklist_date = target_date
    AND deleted_at IS NULL;

  RETURN QUERY
  WITH src AS (
    SELECT
      y.item_id,
      y.sort_order,
      y.tb_tyapp_dcl_day_seq_no,
      row_number() OVER (
        ORDER BY y.sort_order ASC, y.tb_tyapp_dcl_day_seq_no ASC
      ) AS rn
    FROM public.tyapp_daily_checklist_day_item y
    WHERE y.user_id = v_uid
      AND y.checklist_date = v_source_date
      AND y.deleted_at IS NULL
      AND NOT EXISTS (
        SELECT 1
        FROM public.tyapp_daily_checklist_day_item d
        WHERE d.user_id = v_uid
          AND d.checklist_date = target_date
          AND d.item_id = y.item_id
          AND d.deleted_at IS NULL
      )
  ),
  ins AS (
    INSERT INTO public.tyapp_daily_checklist_day_item (
      user_id,
      item_id,
      checklist_date,
      sort_order,
      status,
      completed_at
    )
    SELECT
      v_uid,
      s.item_id,
      target_date,
      v_base + s.rn::integer,
      1,
      NULL
    FROM src s
    ORDER BY s.rn
    RETURNING *
  )
  SELECT *
  FROM ins
  ORDER BY sort_order ASC, tb_tyapp_dcl_day_seq_no ASC;
END;
$$;

CREATE OR REPLACE FUNCTION public.tyapp_daily_checklist_create_from_standard(
  target_date date
)
RETURNS SETOF public.tyapp_daily_checklist_day_item
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_base integer;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF target_date IS NULL THEN
    RAISE EXCEPTION 'target_date is required';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.tyapp_daily_checklist_standard_item
    WHERE user_id = v_uid
      AND deleted_at IS NULL
  ) THEN
    RAISE EXCEPTION 'Your Standard Checklist is empty. Add items on the Standard Checklist page first.';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.tyapp_daily_checklist_standard_item s
    WHERE s.user_id = v_uid
      AND s.deleted_at IS NULL
      AND NOT EXISTS (
        SELECT 1
        FROM public.tyapp_daily_checklist_day_item d
        WHERE d.user_id = v_uid
          AND d.checklist_date = target_date
          AND d.item_id = s.item_id
          AND d.deleted_at IS NULL
      )
  ) THEN
    RAISE EXCEPTION 'All standard items are already on this date.';
  END IF;

  SELECT COALESCE(MAX(sort_order), -1)
  INTO v_base
  FROM public.tyapp_daily_checklist_day_item
  WHERE user_id = v_uid
    AND checklist_date = target_date
    AND deleted_at IS NULL;

  RETURN QUERY
  WITH src AS (
    SELECT
      s.item_id,
      s.sort_order,
      s.tb_tyapp_dcl_std_seq_no,
      row_number() OVER (
        ORDER BY s.sort_order ASC, s.tb_tyapp_dcl_std_seq_no ASC
      ) AS rn
    FROM public.tyapp_daily_checklist_standard_item s
    WHERE s.user_id = v_uid
      AND s.deleted_at IS NULL
      AND NOT EXISTS (
        SELECT 1
        FROM public.tyapp_daily_checklist_day_item d
        WHERE d.user_id = v_uid
          AND d.checklist_date = target_date
          AND d.item_id = s.item_id
          AND d.deleted_at IS NULL
      )
  ),
  ins AS (
    INSERT INTO public.tyapp_daily_checklist_day_item (
      user_id,
      item_id,
      checklist_date,
      sort_order,
      status,
      completed_at
    )
    SELECT
      v_uid,
      src.item_id,
      target_date,
      v_base + src.rn::integer,
      1,
      NULL
    FROM src
    ORDER BY src.rn
    RETURNING *
  )
  SELECT *
  FROM ins
  ORDER BY sort_order ASC, tb_tyapp_dcl_day_seq_no ASC;
END;
$$;

GRANT EXECUTE ON FUNCTION public.tyapp_daily_checklist_copy_previous_day(date)
  TO authenticated;
GRANT EXECUTE ON FUNCTION public.tyapp_daily_checklist_create_from_standard(date)
  TO authenticated;

-- ---------------------------------------------------------------------------
-- App Feature registry (no automatic user grants)
-- ---------------------------------------------------------------------------

INSERT INTO public.tyapp_app_feature (
  app_id,
  name,
  icon,
  route,
  remarks,
  status,
  show_in_launcher,
  is_admin_only,
  customized_order
)
SELECT
  (SELECT tb_tyapp_app_id FROM public.tyapp_app WHERE name = 'Jaxfr' AND deleted_at IS NULL LIMIT 1),
  'Daily Checklist',
  'checklist',
  '/daily-checklist',
  'Personal dated work checklist',
  1,
  true,
  false,
  (SELECT COALESCE(MAX(customized_order), 0) + 1 FROM public.tyapp_app_feature)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.tyapp_app_feature
  WHERE name = 'Daily Checklist'
    AND deleted_at IS NULL
);

UPDATE public.tyapp_app_feature
SET
  icon = 'checklist',
  route = '/daily-checklist',
  is_admin_only = false,
  show_in_launcher = true,
  status = 1,
  remarks = COALESCE(remarks, 'Personal dated work checklist'),
  updated_at = now()
WHERE name = 'Daily Checklist'
  AND deleted_at IS NULL;

NOTIFY pgrst, 'reload schema';
