-- Safe patch for an already-created Daily Checklist database.
-- Adds per-day mood/title log, optional view grants, and SELECT-only sharing.
-- Does not drop tables. Paste into the Supabase SQL Editor and run.
-- Requires tyapp_user_ids_share_a_group() from user-group.schema.sql.

-- ---------------------------------------------------------------------------
-- Day log: one mood + title per user per date
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.tyapp_daily_checklist_day (
  tb_tyapp_dcl_dly_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_dcl_dly_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES auth.users (id),
  checklist_date date NOT NULL,
  mood_key text,
  title text,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_daily_checklist_day_mood_key
    CHECK (mood_key IS NULL OR mood_key IN (
      'green', 'gold', 'red', 'blue', 'purple'
    ))
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_daily_checklist_day_user_date_uniq
  ON public.tyapp_daily_checklist_day (user_id, checklist_date)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_daily_checklist_day_user_date_idx
  ON public.tyapp_daily_checklist_day (user_id, checklist_date)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS tyapp_daily_checklist_day_set_updated_at
  ON public.tyapp_daily_checklist_day;
CREATE TRIGGER tyapp_daily_checklist_day_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_daily_checklist_day
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Share grants: owner allows viewer to read owner's day logs + day items
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.tyapp_daily_checklist_share (
  tb_tyapp_dcl_shr_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_dcl_shr_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  owner_user_id uuid NOT NULL REFERENCES auth.users (id),
  viewer_user_id uuid NOT NULL REFERENCES auth.users (id),
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_daily_checklist_share_not_self
    CHECK (owner_user_id <> viewer_user_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_daily_checklist_share_pair_uniq
  ON public.tyapp_daily_checklist_share (owner_user_id, viewer_user_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_daily_checklist_share_viewer_idx
  ON public.tyapp_daily_checklist_share (viewer_user_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS tyapp_daily_checklist_share_set_updated_at
  ON public.tyapp_daily_checklist_share;
CREATE TRIGGER tyapp_daily_checklist_share_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_daily_checklist_share
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.tyapp_daily_checklist_share_enforce_group()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.tyapp_user_ids_share_a_group(
    ARRAY[NEW.owner_user_id, NEW.viewer_user_id]
  ) THEN
    RAISE EXCEPTION 'Everyone granted access must belong to the same user group';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tyapp_daily_checklist_share_enforce_group
  ON public.tyapp_daily_checklist_share;
CREATE TRIGGER tyapp_daily_checklist_share_enforce_group
  BEFORE INSERT OR UPDATE OF owner_user_id, viewer_user_id
  ON public.tyapp_daily_checklist_share
  FOR EACH ROW
  EXECUTE FUNCTION public.tyapp_daily_checklist_share_enforce_group();

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

ALTER TABLE public.tyapp_daily_checklist_day ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_daily_checklist_day FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE ON public.tyapp_daily_checklist_day TO authenticated;

ALTER TABLE public.tyapp_daily_checklist_share ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_daily_checklist_share FROM PUBLIC, anon;
GRANT SELECT, INSERT, UPDATE ON public.tyapp_daily_checklist_share TO authenticated;

DROP POLICY IF EXISTS tyapp_daily_checklist_share_select
  ON public.tyapp_daily_checklist_share;
DROP POLICY IF EXISTS tyapp_daily_checklist_share_insert
  ON public.tyapp_daily_checklist_share;
DROP POLICY IF EXISTS tyapp_daily_checklist_share_update
  ON public.tyapp_daily_checklist_share;
DROP POLICY IF EXISTS tyapp_daily_checklist_day_select
  ON public.tyapp_daily_checklist_day;
DROP POLICY IF EXISTS tyapp_daily_checklist_day_insert
  ON public.tyapp_daily_checklist_day;
DROP POLICY IF EXISTS tyapp_daily_checklist_day_update
  ON public.tyapp_daily_checklist_day;
DROP POLICY IF EXISTS tyapp_daily_checklist_item_select
  ON public.tyapp_daily_checklist_item;
DROP POLICY IF EXISTS tyapp_daily_checklist_day_item_select
  ON public.tyapp_daily_checklist_day_item;

CREATE POLICY tyapp_daily_checklist_share_select
  ON public.tyapp_daily_checklist_share
  FOR SELECT
  TO authenticated
  USING (
    deleted_at IS NULL
    AND (owner_user_id = auth.uid() OR viewer_user_id = auth.uid())
  );

CREATE POLICY tyapp_daily_checklist_share_insert
  ON public.tyapp_daily_checklist_share
  FOR INSERT
  TO authenticated
  WITH CHECK (owner_user_id = auth.uid());

CREATE POLICY tyapp_daily_checklist_share_update
  ON public.tyapp_daily_checklist_share
  FOR UPDATE
  TO authenticated
  USING (owner_user_id = auth.uid() AND deleted_at IS NULL)
  WITH CHECK (owner_user_id = auth.uid());

CREATE POLICY tyapp_daily_checklist_day_select
  ON public.tyapp_daily_checklist_day
  FOR SELECT
  TO authenticated
  USING (
    deleted_at IS NULL
    AND (
      user_id = auth.uid()
      OR EXISTS (
        SELECT 1
        FROM public.tyapp_daily_checklist_share s
        WHERE s.owner_user_id = user_id
          AND s.viewer_user_id = auth.uid()
          AND s.deleted_at IS NULL
      )
    )
  );

CREATE POLICY tyapp_daily_checklist_day_insert
  ON public.tyapp_daily_checklist_day
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY tyapp_daily_checklist_day_update
  ON public.tyapp_daily_checklist_day
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL)
  WITH CHECK (user_id = auth.uid());

CREATE POLICY tyapp_daily_checklist_item_select
  ON public.tyapp_daily_checklist_item
  FOR SELECT
  TO authenticated
  USING (
    deleted_at IS NULL
    AND (
      user_id = auth.uid()
      OR EXISTS (
        SELECT 1
        FROM public.tyapp_daily_checklist_share s
        WHERE s.owner_user_id = user_id
          AND s.viewer_user_id = auth.uid()
          AND s.deleted_at IS NULL
      )
    )
  );

CREATE POLICY tyapp_daily_checklist_day_item_select
  ON public.tyapp_daily_checklist_day_item
  FOR SELECT
  TO authenticated
  USING (
    deleted_at IS NULL
    AND (
      user_id = auth.uid()
      OR EXISTS (
        SELECT 1
        FROM public.tyapp_daily_checklist_share s
        WHERE s.owner_user_id = user_id
          AND s.viewer_user_id = auth.uid()
          AND s.deleted_at IS NULL
      )
    )
  );

-- ---------------------------------------------------------------------------
-- Soft-delete RPCs
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.tyapp_daily_checklist_share_soft_delete_single_record(
  record_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_found uuid;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT tb_tyapp_dcl_shr_id
  INTO v_found
  FROM public.tyapp_daily_checklist_share
  WHERE tb_tyapp_dcl_shr_id = record_id
    AND owner_user_id = v_uid
    AND deleted_at IS NULL;

  IF v_found IS NULL THEN
    RAISE EXCEPTION 'Share grant not found or inaccessible';
  END IF;

  UPDATE public.tyapp_daily_checklist_share
  SET deleted_at = now()
  WHERE tb_tyapp_dcl_shr_id = record_id
    AND owner_user_id = v_uid
    AND deleted_at IS NULL;
END;
$$;

GRANT EXECUTE ON FUNCTION public.tyapp_daily_checklist_share_soft_delete_single_record(uuid)
  TO authenticated;

NOTIFY pgrst, 'reload schema';
