-- TyWeb v5 public-site singleton settings.
-- Paste into the Supabase SQL editor (safe to re-run).
--
-- The table already has one live row. This file restates the DDL, replaces
-- RLS, and registers the Jaxfr launcher feature "TyWeb".
--
-- Access:
--   authenticated  SELECT + UPDATE on the live row (any logged-in user).
--                  Jaxfr still gates the page with featureAccessGuard.
--   anon           SELECT the published live row so the public site can
--                  read notice / popup / contact without a login.
--   No INSERT / DELETE via the API — recreate the singleton in SQL if needed.
--
-- The older launcher-off feature named "Tyweb" is a log-only tag for the
-- archived content manager. Leave it alone; this inserts a new "TyWeb" row.

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.tyweb_v5_settings (
  tb_tyweb_v5_stng_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyweb_v5_stng_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  singleton_key smallint NOT NULL DEFAULT 1,
  notice_enabled boolean NOT NULL DEFAULT false,
  notice_message text,
  notice_dismissible boolean NOT NULL DEFAULT true,
  popup_enabled boolean NOT NULL DEFAULT false,
  popup_title text,
  popup_message text,
  contact_email text,
  linkedin_url text,
  github_url text,
  resume_url text,
  remarks text,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyweb_v5_settings_singleton_key_chk CHECK (singleton_key = 1)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tyweb_v5_settings_singleton_active
  ON public.tyweb_v5_settings (singleton_key)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS tyweb_v5_settings_set_updated_at
  ON public.tyweb_v5_settings;
CREATE TRIGGER tyweb_v5_settings_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyweb_v5_settings
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

INSERT INTO public.tyweb_v5_settings (singleton_key)
SELECT 1
WHERE NOT EXISTS (
  SELECT 1
  FROM public.tyweb_v5_settings
  WHERE singleton_key = 1
    AND deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- RLS (replace whatever is currently on this table)
-- ---------------------------------------------------------------------------

ALTER TABLE public.tyweb_v5_settings ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  pol record;
BEGIN
  FOR pol IN
    SELECT policyname
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'tyweb_v5_settings'
  LOOP
    EXECUTE format(
      'DROP POLICY IF EXISTS %I ON public.tyweb_v5_settings',
      pol.policyname
    );
  END LOOP;
END $$;

REVOKE ALL ON public.tyweb_v5_settings FROM PUBLIC, anon, authenticated;
GRANT SELECT, UPDATE ON public.tyweb_v5_settings TO authenticated;
GRANT SELECT ON public.tyweb_v5_settings TO anon;

CREATE POLICY tyweb_v5_settings_authenticated_select
  ON public.tyweb_v5_settings
  FOR SELECT
  TO authenticated
  USING (deleted_at IS NULL);

CREATE POLICY tyweb_v5_settings_authenticated_update
  ON public.tyweb_v5_settings
  FOR UPDATE
  TO authenticated
  USING (deleted_at IS NULL)
  WITH CHECK (deleted_at IS NULL);

CREATE POLICY tyweb_v5_settings_anon_select
  ON public.tyweb_v5_settings
  FOR SELECT
  TO anon
  USING (deleted_at IS NULL AND status = 1);

-- ---------------------------------------------------------------------------
-- Jaxfr launcher feature
-- ---------------------------------------------------------------------------

INSERT INTO public.tyapp_app_feature (
  app_id, name, icon, route, is_admin_only, show_in_launcher, customized_order
)
SELECT
  (SELECT tb_tyapp_app_id FROM public.tyapp_app WHERE name = 'Jaxfr' LIMIT 1),
  'TyWeb',
  'web',
  '/tyweb',
  false,
  true,
  COALESCE(
    (
      SELECT MAX(customized_order)
      FROM public.tyapp_app_feature
      WHERE deleted_at IS NULL
    ),
    0
  ) + 1
WHERE NOT EXISTS (
  SELECT 1
  FROM public.tyapp_app_feature
  WHERE name = 'TyWeb'
    AND deleted_at IS NULL
);
