-- Jaxfr app-wide singleton settings.
-- Paste into the Supabase SQL editor (safe to re-run).
-- Add new columns here as features need them — do not create per-feature
-- settings tables.
--
-- Change values with UPDATE, e.g.:
--   UPDATE public.tyapp_app_settings
--   SET chat_delete_window_ms = 600000
--   WHERE singleton_key = 1 AND deleted_at IS NULL;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.tyapp_app_settings (
  tb_tyapp_app_stng_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_app_stng_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  singleton_key smallint NOT NULL DEFAULT 1,
  chat_edit_window_ms integer NOT NULL DEFAULT 300000
    CHECK (chat_edit_window_ms > 0),
  chat_delete_window_ms integer NOT NULL DEFAULT 300000
    CHECK (chat_delete_window_ms > 0),
  remarks text,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_app_settings_singleton_key_chk CHECK (singleton_key = 1)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tyapp_app_settings_singleton_active
  ON public.tyapp_app_settings (singleton_key)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS tyapp_app_settings_set_updated_at
  ON public.tyapp_app_settings;
CREATE TRIGGER tyapp_app_settings_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_app_settings
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

INSERT INTO public.tyapp_app_settings (
  singleton_key,
  chat_edit_window_ms,
  chat_delete_window_ms
)
SELECT 1, 300000, 300000
WHERE NOT EXISTS (
  SELECT 1
  FROM public.tyapp_app_settings
  WHERE singleton_key = 1
    AND deleted_at IS NULL
);

ALTER TABLE public.tyapp_app_settings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_app_settings FROM PUBLIC, anon;
GRANT SELECT ON public.tyapp_app_settings TO authenticated;

DROP POLICY IF EXISTS tyapp_app_settings_select ON public.tyapp_app_settings;
CREATE POLICY tyapp_app_settings_select
  ON public.tyapp_app_settings
  FOR SELECT
  TO authenticated
  USING (deleted_at IS NULL AND status = 1);
