import { CommonModule } from '@angular/common';
import { Component, OnInit, OnDestroy, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { Router, ActivatedRoute, RouterModule } from '@angular/router';

import { HeaderService } from '../../../../core/services/header.service';
import { NotificationService } from '../../../../core/services/notification.service';
import { FitService } from './fit.service';
import { MatCardModule } from '@angular/material/card';
import { RecordStatus } from '../../../../core/models/status.enum';
import { FitThreadFormatterUtil } from './fit-thread-formatter.util';

type FitThreadItemVm = {
  id: string;
  sessionDate: string;
  title: string;
  text: string;
  status: number;
};

@Component({
  selector: 'app-fit-thread',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatCardModule,
  ],
  templateUrl: './fit-thread.html',
  styleUrl: './fit-thread.scss',
})
export class FitThread implements OnInit, OnDestroy {
  public fitService = inject(FitService);
  private headerService = inject(HeaderService);
  private notificationService = inject(NotificationService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);

  readonly RecordStatus = RecordStatus;

  loading = signal(false);
  threadItems = signal<FitThreadItemVm[]>([]);

  ngOnInit() {
    this.headerService.setConfig({
      actions: [
        {
          label: 'Refresh',
          icon: 'refresh',
          type: 'secondary',
          onClick: () => this.loadThread(),
        },
        {
          label: 'New Session',
          icon: 'add',
          type: 'primary',
          onClick: () =>
            this.router.navigate(['../new'], { relativeTo: this.route }),
        },
      ],
    });

    this.loadThread();
  }

  ngOnDestroy() {
    this.headerService.clear();
  }

  async loadThread() {
    this.loading.set(true);
    try {
      const details = await this.fitService.fetchRecentThreadDetails(15);

      const items = details.map((detail) => ({
        id: detail.session.tb_tyapp_fit_ssn_id,
        sessionDate: detail.session.session_date,
        title: detail.session.session_title?.trim() || 'Untitled Session',
        status: detail.session.status,
        text: FitThreadFormatterUtil.format(detail),
      }));

      this.threadItems.set(items);
    } finally {
      this.loading.set(false);
    }
  }

  onEdit(id: string) {
    this.router.navigate(['../edit', id], {
      relativeTo: this.route,
      queryParams: { returnUrl: '/fit/thread' },
    });
  }

  async copyText(text: string) {
    try {
      await navigator.clipboard.writeText(
        '[This content is generated by TY Web App]\n' + text,
      );
      this.notificationService.showSuccess('已複製到剪貼簿');
    } catch (err) {
      this.notificationService.handleError('複製失敗，請手動選取', err);
    }
  }
}
