import { CommonModule } from '@angular/common';
import { Component, OnInit, OnDestroy, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { Router, ActivatedRoute, RouterModule } from '@angular/router';

import { HeaderService } from '../../../../core/services/header.service';
import { NotificationService } from '../../../../core/services/notification.service';
import { FitService } from './fit.service';
import { FitSessionDetail, FitSideCode } from './fit.model';
import { MatCardModule } from '@angular/material/card';
import { RecordStatus } from '../../../../core/models/status.enum';

type FitThreadItemVm = {
  id: string;
  sessionDate: string;
  title: string;
  text: string;
  status: number;
};

@Component({
  selector: 'app-fit-thread',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatCardModule,
  ],
  templateUrl: './fit-thread.html',
  styleUrl: './fit-thread.scss',
})
export class FitThread implements OnInit, OnDestroy {
  public fitService = inject(FitService);
  private headerService = inject(HeaderService);
  private notificationService = inject(NotificationService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);

  readonly RecordStatus = RecordStatus;

  loading = signal(false);
  threadItems = signal<FitThreadItemVm[]>([]);

  ngOnInit() {
    this.headerService.setConfig({
      actions: [
        {
          label: 'Refresh',
          icon: 'refresh',
          type: 'secondary',
          onClick: () => this.loadThread(),
        },
        {
          label: 'New Session',
          icon: 'add',
          type: 'primary',
          onClick: () =>
            this.router.navigate(['../new'], { relativeTo: this.route }),
        },
      ],
    });

    this.loadThread();
  }

  ngOnDestroy() {
    this.headerService.clear();
  }

  async loadThread() {
    this.loading.set(true);
    try {
      const details = await this.fitService.fetchRecentThreadDetails(15);

      const items = details.map((detail) => ({
        id: detail.session.tb_tyapp_fit_ssn_id,
        sessionDate: detail.session.session_date,
        title: detail.session.session_title?.trim() || 'Untitled Session',
        status: detail.session.status,
        text: this.buildThreadText(detail),
      }));

      this.threadItems.set(items);
    } finally {
      this.loading.set(false);
    }
  }

  onEdit(id: string) {
    this.router.navigate(['../edit', id], {
      relativeTo: this.route,
      queryParams: { returnUrl: '/fit/thread' },
    });
  }

  async copyText(text: string) {
    try {
      await navigator.clipboard.writeText(
        '[This content is generated by TY Web App]\n' + text,
      );
      this.notificationService.showSuccess('已複製到剪貼簿');
    } catch (err) {
      this.notificationService.handleError('複製失敗，請手動選取', err);
    }
  }

  private buildThreadText(detail: FitSessionDetail): string {
    const lines: string[] = [];
    const session = detail.session;

    let header = `${session.session_date}：`;
    if (session.session_title?.trim()) {
      header += `\n${session.session_title.trim()}`;
    }
    lines.push(header);

    if (session.location?.trim()) {
      lines.push(`📍 ${session.location.trim()}`);
    }

    if (session.remarks?.trim()) {
      lines.push(session.remarks.trim());
    }
    lines.push('');

    detail.entries.forEach((entry) => {
      const typeLabel = this.getEntryTypeLabel(entry.entry_type);
      lines.push(`${entry.exercise_name || '未命名動作'} (${typeLabel})`);

      if (entry.source_url?.trim()) {
        lines.push(`🔗 ${entry.source_url.trim()}`);
      }

      if (entry.entry_type === 'cardio') {
        entry.sets.forEach((set, index) => {
          if (index > 0) lines.push('');

          if (set.duration_sec !== null) {
            const mins = Math.floor(set.duration_sec / 60);
            const secs = set.duration_sec % 60;
            lines.push(
              `時間 ${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`,
            );
          }
          if (set.calories_value !== null) {
            lines.push(`Calories ${set.calories_value}`);
          }
          if (set.distance_value !== null) {
            lines.push(`距離 ${set.distance_value}${set.distance_unit || ''}`);
          }
          if (set.level_text?.trim()) {
            lines.push(`Level ${set.level_text.trim()}`);
          }
          if (set.incline_value !== null) {
            lines.push(`坡度 ${set.incline_value}`);
          }
          if (set.side_code) {
            lines.push(this.getSideLabel(set.side_code));
          }
          if (set.remarks?.trim()) {
            lines.push(`備註：${set.remarks.trim()}`);
          }
        });
      } else {
        const groupedSets: {
          side: string;
          core: string;
          remarks: string;
          count: number;
        }[] = [];
        let currentGroup: {
          side: string;
          core: string;
          remarks: string;
          count: number;
        } | null = null;

        entry.sets.forEach((set) => {
          const sideStr = set.side_code
            ? `${this.getSideLabel(set.side_code)} `
            : '';

          let coreStr = '';
          if (set.weight_value !== null)
            coreStr += `${set.weight_value}${set.weight_unit || ''}`;
          if (set.reps_value !== null)
            coreStr += coreStr ? `×${set.reps_value}` : `${set.reps_value}下`;
          if (set.duration_sec !== null) {
            const mins = Math.floor(set.duration_sec / 60);
            const secs = set.duration_sec % 60;
            const timeStr = mins > 0 ? `${mins}分${secs}秒` : `${secs}秒`;
            coreStr += coreStr ? ` · ${timeStr}` : timeStr;
          }
          if (!coreStr) coreStr = '完成';

          const remarkStr = set.remarks?.trim()
            ? ` (${set.remarks.trim()})`
            : '';

          if (
            currentGroup &&
            currentGroup.side === sideStr &&
            currentGroup.core === coreStr &&
            currentGroup.remarks === remarkStr
          ) {
            currentGroup.count++;
          } else {
            if (currentGroup) groupedSets.push(currentGroup);
            currentGroup = {
              side: sideStr,
              core: coreStr,
              remarks: remarkStr,
              count: 1,
            };
          }
        });

        if (currentGroup) groupedSets.push(currentGroup);

        groupedSets.forEach((g) => {
          let line = `${g.side}${g.core}`;
          if (g.count > 1) {
            line += `×${g.count}`;
          }
          line += g.remarks;
          lines.push(line);
        });
      }

      if (entry.remarks?.trim()) {
        lines.push(`💡 ${entry.remarks.trim()}`);
      }
      lines.push('');
    });

    return lines.join('\n').trim();
  }

  private getEntryTypeLabel(type: string): string {
    const map: Record<string, string> = {
      strength: '重量訓練',
      cardio: '有氧',
      mobility: '伸展',
      bodyweight: '自體重',
    };
    return map[type] || type;
  }

  private getSideLabel(side: FitSideCode): string {
    if (side === 'left') return '左手/左腳';
    if (side === 'right') return '右手/右腳';
    return '雙側';
  }
}
