-- If you already applied an earlier Doc Sign schema, re-run
-- docsign.schema.sql in the same folder (it is safe to re-run).
-- Adds exclusive open (claim_edit raises if busy), signed_mark,
-- signature profiles, edit leases, and sign_and_send.
