-- Bill share rows. Safe to re-run.
-- Paste in the Supabase SQL editor (the table already enables RLS).
-- Backfill: cty/frd ownership -> one 1.0 row; NULL ownership -> 0.5 for each bound user.

CREATE TABLE IF NOT EXISTS public.tyapp_yyems_bill_share (
  tb_tyapp_ybs_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_ybs_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  yyems_id uuid NOT NULL
    REFERENCES public.tyapp_yyems (tb_tyapp_yym_id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.tyapp_user (user_id),
  share numeric NOT NULL,
  CONSTRAINT tyapp_yyems_bill_share_ok CHECK (share > 0 AND share <= 1),
  CONSTRAINT tyapp_yyems_bill_share_user_uniq UNIQUE (yyems_id, user_id)
);

CREATE INDEX IF NOT EXISTS tyapp_yyems_bill_share_bill_idx
  ON public.tyapp_yyems_bill_share (yyems_id);

ALTER TABLE public.tyapp_yyems_bill_share ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_yyems_bill_share FROM PUBLIC, anon;
GRANT SELECT, INSERT, DELETE ON public.tyapp_yyems_bill_share TO authenticated;

DROP POLICY IF EXISTS tyapp_yyems_household_select_share
  ON public.tyapp_yyems_bill_share;
CREATE POLICY tyapp_yyems_household_select_share
  ON public.tyapp_yyems_bill_share
  FOR SELECT TO authenticated
  USING (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_ins_share
  ON public.tyapp_yyems_bill_share;
CREATE POLICY tyapp_yyems_household_ins_share
  ON public.tyapp_yyems_bill_share
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_del_share
  ON public.tyapp_yyems_bill_share;
CREATE POLICY tyapp_yyems_household_del_share
  ON public.tyapp_yyems_bill_share
  FOR DELETE TO authenticated
  USING (public.tyapp_yyems_is_household_member());

INSERT INTO public.tyapp_yyems_bill_share (yyems_id, user_id, share)
SELECT b.tb_tyapp_yym_id, b.ownership_user_id, 1
FROM public.tyapp_yyems b
WHERE b.deleted_at IS NULL
  AND b.ownership_user_id IS NOT NULL
ON CONFLICT (yyems_id, user_id) DO NOTHING;

INSERT INTO public.tyapp_yyems_bill_share (yyems_id, user_id, share)
SELECT b.tb_tyapp_yym_id, u.user_id, 0.5
FROM public.tyapp_yyems b
CROSS JOIN public.tyapp_user u
WHERE b.deleted_at IS NULL
  AND b.ownership_user_id IS NULL
  AND u.deleted_at IS NULL
  AND lower(btrim(coalesce(u.appsheet_525_user_id, ''))) IN ('cty', 'frd')
ON CONFLICT (yyems_id, user_id) DO NOTHING;
