-- Bill share rows. Safe to re-run.
-- Paste in the Supabase SQL editor (the table already enables RLS).
-- Phase D: tyapp_yyhome has no ownership_user_id. Share rows come from the app
-- (replaceBillShares) and Excel import — do not backfill from a bill column.

CREATE TABLE IF NOT EXISTS public.tyapp_yyhome_bill_share (
  tb_tyapp_yhbs_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yhbs_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  yyhome_id uuid NOT NULL
    REFERENCES public.tyapp_yyhome (tb_tyapp_yhm_id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.tyapp_user (user_id),
  share numeric NOT NULL,
  CONSTRAINT tyapp_yyhome_bill_share_ok CHECK (share > 0 AND share <= 1),
  CONSTRAINT tyapp_yyhome_bill_share_user_uniq UNIQUE (yyhome_id, user_id)
);

CREATE INDEX IF NOT EXISTS tyapp_yyhome_bill_share_bill_idx
  ON public.tyapp_yyhome_bill_share (yyhome_id);

ALTER TABLE public.tyapp_yyhome_bill_share ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tyapp_yyhome_bill_share FROM PUBLIC, anon;
GRANT SELECT, INSERT, DELETE ON public.tyapp_yyhome_bill_share TO authenticated;

DROP POLICY IF EXISTS tyapp_yyhome_household_select_share
  ON public.tyapp_yyhome_bill_share;
CREATE POLICY tyapp_yyhome_household_select_share
  ON public.tyapp_yyhome_bill_share
  FOR SELECT TO authenticated
  USING (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_ins_share
  ON public.tyapp_yyhome_bill_share;
CREATE POLICY tyapp_yyhome_household_ins_share
  ON public.tyapp_yyhome_bill_share
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_del_share
  ON public.tyapp_yyhome_bill_share;
CREATE POLICY tyapp_yyhome_household_del_share
  ON public.tyapp_yyhome_bill_share
  FOR DELETE TO authenticated
  USING (public.tyapp_yyhome_is_household_member());
