-- OBSOLETE (AppSheet ownership revert).
-- bill_share is gone. Ownership lives on tyapp_yyhome_bill.ownership (cty|frd|yyems).
-- Do not run this file. Use yyhome.drop-yyems.sql + yyems.schema.sql instead.
