-- Jaxfr yyHome household ledger — Phase D schema (tyapp_yyhome_*).
-- Run AFTER yyhome.drop-yyems.sql. Safe-ish to re-run CREATE OR REPLACE pieces;
-- tables use IF NOT EXISTS (drop first if recreating).
--
-- Display name yyHome. App folder/routes still /yyems until a later rename.
-- Access: appsheet_525_user_id, a yyHome / YYEMS feature grant, or Super Admin.
-- People: cty/frd from AppSheet map to tyapp_user.user_id (UUID).
-- Who bears a bill: tyapp_yyhome_bill_share only (no ownership_user_id on the bill).
-- Both = two 0.5 rows. One person = one 1.0 row. Excel party code "yyems" is NOT a login.
--
-- Files: Google Drive file id on tyapp_yyhome_file (see multimedia strategy).
-- No Supabase Storage in this schema.

-- ---------------------------------------------------------------------------
-- Household gate
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.tyapp_yyhome_is_household_member()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    public.tyapp_is_super_admin()
    OR EXISTS (
      SELECT 1
      FROM public.tyapp_user u
      WHERE u.user_id = auth.uid()
        AND u.deleted_at IS NULL
        AND u.appsheet_525_user_id IS NOT NULL
        AND length(btrim(u.appsheet_525_user_id)) > 0
    )
    OR EXISTS (
      SELECT 1
      FROM public.tyapp_user_feature_access g
      JOIN public.tyapp_app_feature f
        ON f.tb_tyapp_ap_ftr_id = g.feature_id
      WHERE g.user_id = auth.uid()
        AND f.deleted_at IS NULL
        AND f.name IN ('yyHome', 'YYEMS')
    ),
    false
  );
$$;

GRANT EXECUTE ON FUNCTION public.tyapp_yyhome_is_household_member() TO authenticated;

-- ---------------------------------------------------------------------------
-- Dictionaries
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.tyapp_yyhome_item_category (
  tb_tyapp_yhic_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yhic_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  code text NOT NULL,
  name_zh text NOT NULL,
  name_en text,
  division text,
  sort_order integer NOT NULL DEFAULT 0,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_yyhome_item_category_code_not_blank
    CHECK (length(btrim(code)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyhome_item_category_legacy_uniq
  ON public.tyapp_yyhome_item_category (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyhome_item_category_code_uniq
  ON public.tyapp_yyhome_item_category (lower(btrim(code)))
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyhome_item (
  tb_tyapp_yhit_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yhit_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  category_id uuid NOT NULL REFERENCES public.tyapp_yyhome_item_category (tb_tyapp_yhic_id),
  name_zh text NOT NULL,
  name_en text,
  food_category text,
  description text,
  plan_buy boolean NOT NULL DEFAULT false,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_yyhome_item_name_not_blank
    CHECK (length(btrim(name_zh)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyhome_item_legacy_uniq
  ON public.tyapp_yyhome_item (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyhome_item_category_idx
  ON public.tyapp_yyhome_item (category_id)
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyhome_vendor_category (
  tb_tyapp_yhvc_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yhvc_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  level1 text NOT NULL,
  level2 text NOT NULL,
  level3 text NOT NULL,
  display_name text NOT NULL,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyhome_vendor_category_legacy_uniq
  ON public.tyapp_yyhome_vendor_category (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyhome_vendor (
  tb_tyapp_yhvd_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yhvd_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  category_id uuid NOT NULL REFERENCES public.tyapp_yyhome_vendor_category (tb_tyapp_yhvc_id),
  name text NOT NULL,
  name_short text,
  sort_order integer,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_yyhome_vendor_name_not_blank
    CHECK (length(btrim(name)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyhome_vendor_legacy_uniq
  ON public.tyapp_yyhome_vendor (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyhome_vendor_category_idx
  ON public.tyapp_yyhome_vendor (category_id)
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyhome_currency (
  code text PRIMARY KEY,
  symbol text NOT NULL,
  CONSTRAINT tyapp_yyhome_currency_code_not_blank
    CHECK (length(btrim(code)) > 0)
);

CREATE TABLE IF NOT EXISTS public.tyapp_yyhome_financial_account (
  tb_tyapp_yhfa_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yhfa_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  -- NULL = household/shared account (legacy Person ID yyems).
  owner_user_id uuid REFERENCES public.tyapp_user (user_id),
  display_name text NOT NULL,
  currency text NOT NULL REFERENCES public.tyapp_yyhome_currency (code),
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyhome_fa_legacy_uniq
  ON public.tyapp_yyhome_financial_account (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyhome_wallet (
  tb_tyapp_yhwl_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yhwl_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  financial_account_id uuid NOT NULL
    REFERENCES public.tyapp_yyhome_financial_account (tb_tyapp_yhfa_id),
  name text NOT NULL,
  sort_order integer,
  remarks text,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_yyhome_wallet_name_not_blank
    CHECK (length(btrim(name)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyhome_wallet_legacy_uniq
  ON public.tyapp_yyhome_wallet (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyhome_wallet_fa_idx
  ON public.tyapp_yyhome_wallet (financial_account_id)
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyhome_fx_rate (
  tb_tyapp_yhfx_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yhfx_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  currency text NOT NULL REFERENCES public.tyapp_yyhome_currency (code),
  year integer NOT NULL,
  to_cad numeric NOT NULL,
  source text,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_yyhome_fx_year_ok CHECK (year BETWEEN 1990 AND 2100)
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyhome_fx_currency_year_uniq
  ON public.tyapp_yyhome_fx_rate (currency, year)
  WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- Main cycle: bill → price → buy → eat
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.tyapp_yyhome (
  tb_tyapp_yhm_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yhm_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  occurred_at timestamptz NOT NULL,
  location_tz text NOT NULL,
  in_or_out text NOT NULL,
  vendor_id uuid NOT NULL REFERENCES public.tyapp_yyhome_vendor (tb_tyapp_yhvd_id),
  currency text NOT NULL REFERENCES public.tyapp_yyhome_currency (code),
  amount numeric NOT NULL,
  wallet_id uuid NOT NULL REFERENCES public.tyapp_yyhome_wallet (tb_tyapp_yhwl_id),
  remark text,
  description text,
  reconciled boolean NOT NULL DEFAULT false,
  -- When bill currency <> wallet account currency, store the wallet-side amount.
  -- Settlement uses wallet_amount if not null, else amount.
  wallet_amount numeric,
  period_start date,
  period_end date,
  created_by uuid NOT NULL REFERENCES public.tyapp_user (user_id),
  -- Group locked at save. Excel rows (legacy_id) are the cty+frd pair, not Ownership.
  group_id uuid REFERENCES public.tyapp_user_group (tb_tyapp_usr_grp_id),
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_yyhome_tz_ok CHECK (location_tz IN ('HK', 'TO')),
  CONSTRAINT tyapp_yyhome_flow_ok CHECK (in_or_out IN ('in', 'out', 'free'))
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyhome_legacy_uniq
  ON public.tyapp_yyhome (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyhome_occurred_idx
  ON public.tyapp_yyhome (occurred_at DESC)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyhome_wallet_idx
  ON public.tyapp_yyhome (wallet_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyhome_group_idx
  ON public.tyapp_yyhome (group_id)
  WHERE deleted_at IS NULL;

-- Who bears this bill. Rows are locked at save time (not "whoever is household now").
-- Both = two rows of 0.5. One person = one row of 1. Shares on a bill sum to 1.
-- Phase D: no ownership_user_id mirror on the bill — list UI derives labels from these rows.
CREATE TABLE IF NOT EXISTS public.tyapp_yyhome_bill_share (
  tb_tyapp_yhbs_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yhbs_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  yyhome_id uuid NOT NULL
    REFERENCES public.tyapp_yyhome (tb_tyapp_yhm_id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.tyapp_user (user_id),
  share numeric NOT NULL,
  CONSTRAINT tyapp_yyhome_bill_share_ok CHECK (share > 0 AND share <= 1),
  CONSTRAINT tyapp_yyhome_bill_share_user_uniq UNIQUE (yyhome_id, user_id)
);

CREATE INDEX IF NOT EXISTS tyapp_yyhome_bill_share_bill_idx
  ON public.tyapp_yyhome_bill_share (yyhome_id);

CREATE TABLE IF NOT EXISTS public.tyapp_yyhome_price (
  tb_tyapp_yhpr_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yhpr_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  priced_at timestamptz NOT NULL,
  vendor_id uuid REFERENCES public.tyapp_yyhome_vendor (tb_tyapp_yhvd_id),
  item_id uuid NOT NULL REFERENCES public.tyapp_yyhome_item (tb_tyapp_yhit_id),
  product_name text,
  product_name_zh text,
  brand text,
  currency text NOT NULL REFERENCES public.tyapp_yyhome_currency (code),
  packed_price numeric,
  tax_rate numeric,
  discount_rate numeric,
  marked_price numeric,
  marked_amount numeric,
  marked_unit text,
  packed_amount numeric,
  packed_unit text,
  tag text,
  is_organic boolean,
  has_msg boolean,
  origin text,
  barcode text,
  barcode_type text,
  remarks text,
  nutri_basis_amount numeric,
  nutri_basis_unit text,
  protein_g numeric,
  carb_g numeric,
  fat_g numeric,
  calories_kcal numeric,
  fiber_g numeric,
  sodium_mg numeric,
  nutri_is_estimated boolean NOT NULL DEFAULT false,
  created_by uuid NOT NULL REFERENCES public.tyapp_user (user_id),
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_yyhome_price_barcode_type_ok
    CHECK (
      barcode_type IS NULL
      OR barcode_type IN ('upc', 'plu', 'price_embedded')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyhome_price_legacy_uniq
  ON public.tyapp_yyhome_price (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyhome_price_item_idx
  ON public.tyapp_yyhome_price (item_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyhome_price_barcode_idx
  ON public.tyapp_yyhome_price (barcode)
  WHERE deleted_at IS NULL AND barcode IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyhome_buy (
  tb_tyapp_yhby_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yhby_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  price_id uuid NOT NULL REFERENCES public.tyapp_yyhome_price (tb_tyapp_yhpr_id),
  yyhome_id uuid REFERENCES public.tyapp_yyhome (tb_tyapp_yhm_id),
  paid numeric,
  home_amount numeric NOT NULL,
  home_unit text,
  marked_amount_count numeric,
  expiry_date date,
  remarks text,
  paid_adjust_note text,
  paid_adjust_reason text,
  eat_priority integer NOT NULL DEFAULT 50,
  created_by uuid NOT NULL REFERENCES public.tyapp_user (user_id),
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyhome_buy_legacy_uniq
  ON public.tyapp_yyhome_buy (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyhome_buy_yyhome_idx
  ON public.tyapp_yyhome_buy (yyhome_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyhome_buy_price_idx
  ON public.tyapp_yyhome_buy (price_id)
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyhome_eat (
  tb_tyapp_yhet_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yhet_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  buy_id uuid NOT NULL REFERENCES public.tyapp_yyhome_buy (tb_tyapp_yhby_id),
  home_amount numeric NOT NULL,
  meal text NOT NULL,
  eaten_by_user_id uuid REFERENCES public.tyapp_user (user_id),
  -- When not a login: shared | dining_out | nil (legacy yyems / 外 / 無).
  eaten_by_other text,
  eat_date date NOT NULL,
  added_at timestamptz NOT NULL DEFAULT now(),
  description text,
  created_by uuid NOT NULL REFERENCES public.tyapp_user (user_id),
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_yyhome_eat_meal_ok CHECK (meal IN (
    '1早', '2茶', '3午', '4茶', '5晚', '6宵', '7用', '8調', '9洗'
  )),
  CONSTRAINT tyapp_yyhome_eat_eaten_by_ok CHECK (
    eaten_by_other IS NULL
    OR eaten_by_other IN ('shared', 'dining_out', 'nil')
  ),
  CONSTRAINT tyapp_yyhome_eat_eaten_by_xor CHECK (
    eaten_by_user_id IS NULL OR eaten_by_other IS NULL
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyhome_eat_legacy_uniq
  ON public.tyapp_yyhome_eat (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyhome_eat_date_idx
  ON public.tyapp_yyhome_eat (eat_date DESC)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyhome_eat_buy_idx
  ON public.tyapp_yyhome_eat (buy_id)
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyhome_file (
  tb_tyapp_yhfl_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yhfl_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  yyhome_id uuid NOT NULL REFERENCES public.tyapp_yyhome (tb_tyapp_yhm_id),
  kind text NOT NULL,
  drive_file_id text,
  legacy_path text,
  original_filename text,
  created_by uuid NOT NULL REFERENCES public.tyapp_user (user_id),
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_yyhome_file_kind_ok CHECK (kind IN ('receipt', 'photo', 'file')),
  CONSTRAINT tyapp_yyhome_file_has_pointer CHECK (
    drive_file_id IS NOT NULL OR legacy_path IS NOT NULL
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyhome_file_legacy_uniq
  ON public.tyapp_yyhome_file (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyhome_file_bill_idx
  ON public.tyapp_yyhome_file (yyhome_id)
  WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- updated_at
-- ---------------------------------------------------------------------------

DROP TRIGGER IF EXISTS tyapp_yyhome_item_category_set_updated_at
  ON public.tyapp_yyhome_item_category;
CREATE TRIGGER tyapp_yyhome_item_category_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyhome_item_category
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyhome_item_set_updated_at
  ON public.tyapp_yyhome_item;
CREATE TRIGGER tyapp_yyhome_item_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyhome_item
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyhome_vendor_category_set_updated_at
  ON public.tyapp_yyhome_vendor_category;
CREATE TRIGGER tyapp_yyhome_vendor_category_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyhome_vendor_category
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyhome_vendor_set_updated_at
  ON public.tyapp_yyhome_vendor;
CREATE TRIGGER tyapp_yyhome_vendor_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyhome_vendor
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyhome_fa_set_updated_at
  ON public.tyapp_yyhome_financial_account;
CREATE TRIGGER tyapp_yyhome_fa_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyhome_financial_account
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyhome_wallet_set_updated_at
  ON public.tyapp_yyhome_wallet;
CREATE TRIGGER tyapp_yyhome_wallet_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyhome_wallet
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyhome_fx_set_updated_at
  ON public.tyapp_yyhome_fx_rate;
CREATE TRIGGER tyapp_yyhome_fx_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyhome_fx_rate
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyhome_set_updated_at
  ON public.tyapp_yyhome;
CREATE TRIGGER tyapp_yyhome_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyhome
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyhome_price_set_updated_at
  ON public.tyapp_yyhome_price;
CREATE TRIGGER tyapp_yyhome_price_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyhome_price
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyhome_buy_set_updated_at
  ON public.tyapp_yyhome_buy;
CREATE TRIGGER tyapp_yyhome_buy_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyhome_buy
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyhome_eat_set_updated_at
  ON public.tyapp_yyhome_eat;
CREATE TRIGGER tyapp_yyhome_eat_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyhome_eat
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyhome_file_set_updated_at
  ON public.tyapp_yyhome_file;
CREATE TRIGGER tyapp_yyhome_file_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyhome_file
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------------------
-- RLS: shared household ledger (both bound users see everything)
-- ---------------------------------------------------------------------------

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'tyapp_yyhome_item_category',
    'tyapp_yyhome_item',
    'tyapp_yyhome_vendor_category',
    'tyapp_yyhome_vendor',
    'tyapp_yyhome_currency',
    'tyapp_yyhome_financial_account',
    'tyapp_yyhome_wallet',
    'tyapp_yyhome_fx_rate',
    'tyapp_yyhome',
    'tyapp_yyhome_bill_share',
    'tyapp_yyhome_price',
    'tyapp_yyhome_buy',
    'tyapp_yyhome_eat',
    'tyapp_yyhome_file'
  ]
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC, anon', t);
    IF t = 'tyapp_yyhome_currency' THEN
      EXECUTE format(
        'GRANT SELECT, INSERT, UPDATE ON public.%I TO authenticated',
        t
      );
    ELSE
      EXECUTE format(
        'GRANT SELECT, INSERT, UPDATE ON public.%I TO authenticated',
        t
      );
    END IF;
  END LOOP;
END;
$$;

DROP POLICY IF EXISTS tyapp_yyhome_currency_select ON public.tyapp_yyhome_currency;
CREATE POLICY tyapp_yyhome_currency_select
  ON public.tyapp_yyhome_currency
  FOR SELECT TO authenticated
  USING (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_currency_write ON public.tyapp_yyhome_currency;
CREATE POLICY tyapp_yyhome_currency_write
  ON public.tyapp_yyhome_currency
  FOR ALL TO authenticated
  USING (public.tyapp_yyhome_is_household_member())
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_select_item_category
  ON public.tyapp_yyhome_item_category;
CREATE POLICY tyapp_yyhome_household_select_item_category
  ON public.tyapp_yyhome_item_category
  FOR SELECT TO authenticated
  USING (public.tyapp_yyhome_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyhome_household_ins_item_category
  ON public.tyapp_yyhome_item_category;
CREATE POLICY tyapp_yyhome_household_ins_item_category
  ON public.tyapp_yyhome_item_category
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_upd_item_category
  ON public.tyapp_yyhome_item_category;
CREATE POLICY tyapp_yyhome_household_upd_item_category
  ON public.tyapp_yyhome_item_category
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyhome_is_household_member())
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_select_item ON public.tyapp_yyhome_item;
CREATE POLICY tyapp_yyhome_household_select_item
  ON public.tyapp_yyhome_item
  FOR SELECT TO authenticated
  USING (public.tyapp_yyhome_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyhome_household_ins_item ON public.tyapp_yyhome_item;
CREATE POLICY tyapp_yyhome_household_ins_item
  ON public.tyapp_yyhome_item
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_upd_item ON public.tyapp_yyhome_item;
CREATE POLICY tyapp_yyhome_household_upd_item
  ON public.tyapp_yyhome_item
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyhome_is_household_member())
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_select_vendor_category
  ON public.tyapp_yyhome_vendor_category;
CREATE POLICY tyapp_yyhome_household_select_vendor_category
  ON public.tyapp_yyhome_vendor_category
  FOR SELECT TO authenticated
  USING (public.tyapp_yyhome_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyhome_household_ins_vendor_category
  ON public.tyapp_yyhome_vendor_category;
CREATE POLICY tyapp_yyhome_household_ins_vendor_category
  ON public.tyapp_yyhome_vendor_category
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_upd_vendor_category
  ON public.tyapp_yyhome_vendor_category;
CREATE POLICY tyapp_yyhome_household_upd_vendor_category
  ON public.tyapp_yyhome_vendor_category
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyhome_is_household_member())
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_select_vendor
  ON public.tyapp_yyhome_vendor;
CREATE POLICY tyapp_yyhome_household_select_vendor
  ON public.tyapp_yyhome_vendor
  FOR SELECT TO authenticated
  USING (public.tyapp_yyhome_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyhome_household_ins_vendor
  ON public.tyapp_yyhome_vendor;
CREATE POLICY tyapp_yyhome_household_ins_vendor
  ON public.tyapp_yyhome_vendor
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_upd_vendor
  ON public.tyapp_yyhome_vendor;
CREATE POLICY tyapp_yyhome_household_upd_vendor
  ON public.tyapp_yyhome_vendor
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyhome_is_household_member())
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_select_fa
  ON public.tyapp_yyhome_financial_account;
CREATE POLICY tyapp_yyhome_household_select_fa
  ON public.tyapp_yyhome_financial_account
  FOR SELECT TO authenticated
  USING (public.tyapp_yyhome_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyhome_household_ins_fa
  ON public.tyapp_yyhome_financial_account;
CREATE POLICY tyapp_yyhome_household_ins_fa
  ON public.tyapp_yyhome_financial_account
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_upd_fa
  ON public.tyapp_yyhome_financial_account;
CREATE POLICY tyapp_yyhome_household_upd_fa
  ON public.tyapp_yyhome_financial_account
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyhome_is_household_member())
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_select_wallet
  ON public.tyapp_yyhome_wallet;
CREATE POLICY tyapp_yyhome_household_select_wallet
  ON public.tyapp_yyhome_wallet
  FOR SELECT TO authenticated
  USING (public.tyapp_yyhome_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyhome_household_ins_wallet
  ON public.tyapp_yyhome_wallet;
CREATE POLICY tyapp_yyhome_household_ins_wallet
  ON public.tyapp_yyhome_wallet
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_upd_wallet
  ON public.tyapp_yyhome_wallet;
CREATE POLICY tyapp_yyhome_household_upd_wallet
  ON public.tyapp_yyhome_wallet
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyhome_is_household_member())
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_select_fx
  ON public.tyapp_yyhome_fx_rate;
CREATE POLICY tyapp_yyhome_household_select_fx
  ON public.tyapp_yyhome_fx_rate
  FOR SELECT TO authenticated
  USING (public.tyapp_yyhome_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyhome_household_ins_fx
  ON public.tyapp_yyhome_fx_rate;
CREATE POLICY tyapp_yyhome_household_ins_fx
  ON public.tyapp_yyhome_fx_rate
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_upd_fx
  ON public.tyapp_yyhome_fx_rate;
CREATE POLICY tyapp_yyhome_household_upd_fx
  ON public.tyapp_yyhome_fx_rate
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyhome_is_household_member())
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_select_bill ON public.tyapp_yyhome;
CREATE POLICY tyapp_yyhome_household_select_bill
  ON public.tyapp_yyhome
  FOR SELECT TO authenticated
  USING (public.tyapp_yyhome_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyhome_household_ins_bill ON public.tyapp_yyhome;
CREATE POLICY tyapp_yyhome_household_ins_bill
  ON public.tyapp_yyhome
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_upd_bill ON public.tyapp_yyhome;
CREATE POLICY tyapp_yyhome_household_upd_bill
  ON public.tyapp_yyhome
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyhome_is_household_member())
  WITH CHECK (public.tyapp_yyhome_is_household_member());

GRANT DELETE ON public.tyapp_yyhome_bill_share TO authenticated;

DROP POLICY IF EXISTS tyapp_yyhome_household_select_share
  ON public.tyapp_yyhome_bill_share;
CREATE POLICY tyapp_yyhome_household_select_share
  ON public.tyapp_yyhome_bill_share
  FOR SELECT TO authenticated
  USING (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_ins_share
  ON public.tyapp_yyhome_bill_share;
CREATE POLICY tyapp_yyhome_household_ins_share
  ON public.tyapp_yyhome_bill_share
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_del_share
  ON public.tyapp_yyhome_bill_share;
CREATE POLICY tyapp_yyhome_household_del_share
  ON public.tyapp_yyhome_bill_share
  FOR DELETE TO authenticated
  USING (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_select_price
  ON public.tyapp_yyhome_price;
CREATE POLICY tyapp_yyhome_household_select_price
  ON public.tyapp_yyhome_price
  FOR SELECT TO authenticated
  USING (public.tyapp_yyhome_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyhome_household_ins_price
  ON public.tyapp_yyhome_price;
CREATE POLICY tyapp_yyhome_household_ins_price
  ON public.tyapp_yyhome_price
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_upd_price
  ON public.tyapp_yyhome_price;
CREATE POLICY tyapp_yyhome_household_upd_price
  ON public.tyapp_yyhome_price
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyhome_is_household_member())
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_select_buy
  ON public.tyapp_yyhome_buy;
CREATE POLICY tyapp_yyhome_household_select_buy
  ON public.tyapp_yyhome_buy
  FOR SELECT TO authenticated
  USING (public.tyapp_yyhome_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyhome_household_ins_buy
  ON public.tyapp_yyhome_buy;
CREATE POLICY tyapp_yyhome_household_ins_buy
  ON public.tyapp_yyhome_buy
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_upd_buy
  ON public.tyapp_yyhome_buy;
CREATE POLICY tyapp_yyhome_household_upd_buy
  ON public.tyapp_yyhome_buy
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyhome_is_household_member())
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_select_eat
  ON public.tyapp_yyhome_eat;
CREATE POLICY tyapp_yyhome_household_select_eat
  ON public.tyapp_yyhome_eat
  FOR SELECT TO authenticated
  USING (public.tyapp_yyhome_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyhome_household_ins_eat
  ON public.tyapp_yyhome_eat;
CREATE POLICY tyapp_yyhome_household_ins_eat
  ON public.tyapp_yyhome_eat
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_upd_eat
  ON public.tyapp_yyhome_eat;
CREATE POLICY tyapp_yyhome_household_upd_eat
  ON public.tyapp_yyhome_eat
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyhome_is_household_member())
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_select_file
  ON public.tyapp_yyhome_file;
CREATE POLICY tyapp_yyhome_household_select_file
  ON public.tyapp_yyhome_file
  FOR SELECT TO authenticated
  USING (public.tyapp_yyhome_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyhome_household_ins_file
  ON public.tyapp_yyhome_file;
CREATE POLICY tyapp_yyhome_household_ins_file
  ON public.tyapp_yyhome_file
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyhome_is_household_member());

DROP POLICY IF EXISTS tyapp_yyhome_household_upd_file
  ON public.tyapp_yyhome_file;
CREATE POLICY tyapp_yyhome_household_upd_file
  ON public.tyapp_yyhome_file
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyhome_is_household_member())
  WITH CHECK (public.tyapp_yyhome_is_household_member());

-- ---------------------------------------------------------------------------
-- Soft delete (no hard DELETE). Household members may delete any row.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.tyapp_yyhome_soft_delete_single_record(record_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF NOT public.tyapp_yyhome_is_household_member() THEN
    RAISE EXCEPTION 'Not a 525 household member';
  END IF;
  UPDATE public.tyapp_yyhome
  SET deleted_at = now()
  WHERE tb_tyapp_yhm_id = record_id AND deleted_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.tyapp_yyhome_price_soft_delete_single_record(record_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF NOT public.tyapp_yyhome_is_household_member() THEN
    RAISE EXCEPTION 'Not a 525 household member';
  END IF;
  UPDATE public.tyapp_yyhome_price
  SET deleted_at = now()
  WHERE tb_tyapp_yhpr_id = record_id AND deleted_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.tyapp_yyhome_buy_soft_delete_single_record(record_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF NOT public.tyapp_yyhome_is_household_member() THEN
    RAISE EXCEPTION 'Not a 525 household member';
  END IF;
  UPDATE public.tyapp_yyhome_buy
  SET deleted_at = now()
  WHERE tb_tyapp_yhby_id = record_id AND deleted_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.tyapp_yyhome_eat_soft_delete_single_record(record_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF NOT public.tyapp_yyhome_is_household_member() THEN
    RAISE EXCEPTION 'Not a 525 household member';
  END IF;
  UPDATE public.tyapp_yyhome_eat
  SET deleted_at = now()
  WHERE tb_tyapp_yhet_id = record_id AND deleted_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.tyapp_yyhome_file_soft_delete_single_record(record_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF NOT public.tyapp_yyhome_is_household_member() THEN
    RAISE EXCEPTION 'Not a 525 household member';
  END IF;
  UPDATE public.tyapp_yyhome_file
  SET deleted_at = now()
  WHERE tb_tyapp_yhfl_id = record_id AND deleted_at IS NULL;
END;
$$;

GRANT EXECUTE ON FUNCTION public.tyapp_yyhome_soft_delete_single_record(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tyapp_yyhome_price_soft_delete_single_record(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tyapp_yyhome_buy_soft_delete_single_record(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tyapp_yyhome_eat_soft_delete_single_record(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tyapp_yyhome_file_soft_delete_single_record(uuid) TO authenticated;

-- Seed codes used by the AppSheet backup (import will reference these).
INSERT INTO public.tyapp_yyhome_currency (code, symbol)
VALUES
  ('CAD', 'CA$'),
  ('HKD', 'HK$'),
  ('USD', 'US$'),
  ('CNY', 'CN¥'),
  ('MOP', 'MOP'),
  ('FREE', 'FREE')
ON CONFLICT (code) DO NOTHING;
