-- Jaxfr 525 / YYEMS household ledger — phase 1 schema (A+B dictionaries + main cycle).
-- Paste into the Supabase SQL editor after review. Safe to re-run table creates
-- use IF NOT EXISTS; helper functions are CREATE OR REPLACE.
--
-- Does NOT import AppSheet rows. Import comes later (legacy_id mapping).
-- Do NOT store AppSheet auto_* / VC display strings; compute those in the app.
--
-- Access: any tyapp_user with appsheet_525_user_id set, or Super Admin.
-- People: cty/frd from AppSheet map to tyapp_user.user_id (UUID).
-- Shared spend: ownership_user_id IS NULL (legacy Person ID "yyems" is NOT a login).
--
-- Files: Google Drive file id on tyapp_yyems_file (see multimedia strategy).
-- No Supabase Storage in this schema.

-- ---------------------------------------------------------------------------
-- Household gate
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.tyapp_yyems_is_household_member()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    public.tyapp_is_super_admin()
    OR EXISTS (
      SELECT 1
      FROM public.tyapp_user u
      WHERE u.user_id = auth.uid()
        AND u.deleted_at IS NULL
        AND u.appsheet_525_user_id IS NOT NULL
        AND length(btrim(u.appsheet_525_user_id)) > 0
    ),
    false
  );
$$;

GRANT EXECUTE ON FUNCTION public.tyapp_yyems_is_household_member() TO authenticated;

-- ---------------------------------------------------------------------------
-- Dictionaries
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.tyapp_yyems_item_category (
  tb_tyapp_yic_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yic_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  code text NOT NULL,
  name_zh text NOT NULL,
  name_en text,
  division text,
  sort_order integer NOT NULL DEFAULT 0,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_yyems_item_category_code_not_blank
    CHECK (length(btrim(code)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyems_item_category_legacy_uniq
  ON public.tyapp_yyems_item_category (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyems_item_category_code_uniq
  ON public.tyapp_yyems_item_category (lower(btrim(code)))
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyems_item (
  tb_tyapp_yit_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yit_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  category_id uuid NOT NULL REFERENCES public.tyapp_yyems_item_category (tb_tyapp_yic_id),
  name_zh text NOT NULL,
  name_en text,
  food_category text,
  description text,
  plan_buy boolean NOT NULL DEFAULT false,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_yyems_item_name_not_blank
    CHECK (length(btrim(name_zh)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyems_item_legacy_uniq
  ON public.tyapp_yyems_item (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyems_item_category_idx
  ON public.tyapp_yyems_item (category_id)
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyems_vendor_category (
  tb_tyapp_yvc_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yvc_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  level1 text NOT NULL,
  level2 text NOT NULL,
  level3 text NOT NULL,
  display_name text NOT NULL,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyems_vendor_category_legacy_uniq
  ON public.tyapp_yyems_vendor_category (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyems_vendor (
  tb_tyapp_yvd_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yvd_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  category_id uuid NOT NULL REFERENCES public.tyapp_yyems_vendor_category (tb_tyapp_yvc_id),
  name text NOT NULL,
  name_short text,
  sort_order integer,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_yyems_vendor_name_not_blank
    CHECK (length(btrim(name)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyems_vendor_legacy_uniq
  ON public.tyapp_yyems_vendor (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyems_vendor_category_idx
  ON public.tyapp_yyems_vendor (category_id)
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyems_currency (
  code text PRIMARY KEY,
  symbol text NOT NULL,
  CONSTRAINT tyapp_yyems_currency_code_not_blank
    CHECK (length(btrim(code)) > 0)
);

CREATE TABLE IF NOT EXISTS public.tyapp_yyems_financial_account (
  tb_tyapp_yfa_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yfa_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  -- NULL = household/shared account (legacy Person ID yyems).
  owner_user_id uuid REFERENCES public.tyapp_user (user_id),
  display_name text NOT NULL,
  currency text NOT NULL REFERENCES public.tyapp_yyems_currency (code),
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyems_fa_legacy_uniq
  ON public.tyapp_yyems_financial_account (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyems_wallet (
  tb_tyapp_ywl_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_ywl_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  financial_account_id uuid NOT NULL
    REFERENCES public.tyapp_yyems_financial_account (tb_tyapp_yfa_id),
  name text NOT NULL,
  sort_order integer,
  remarks text,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_yyems_wallet_name_not_blank
    CHECK (length(btrim(name)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyems_wallet_legacy_uniq
  ON public.tyapp_yyems_wallet (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyems_wallet_fa_idx
  ON public.tyapp_yyems_wallet (financial_account_id)
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyems_fx_rate (
  tb_tyapp_yfx_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yfx_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  currency text NOT NULL REFERENCES public.tyapp_yyems_currency (code),
  year integer NOT NULL,
  to_cad numeric NOT NULL,
  source text,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_yyems_fx_year_ok CHECK (year BETWEEN 1990 AND 2100)
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyems_fx_currency_year_uniq
  ON public.tyapp_yyems_fx_rate (currency, year)
  WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- Main cycle: bill → price → buy → eat
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.tyapp_yyems (
  tb_tyapp_yym_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yym_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  occurred_at timestamptz NOT NULL,
  location_tz text NOT NULL,
  in_or_out text NOT NULL,
  vendor_id uuid NOT NULL REFERENCES public.tyapp_yyems_vendor (tb_tyapp_yvd_id),
  currency text NOT NULL REFERENCES public.tyapp_yyems_currency (code),
  amount numeric NOT NULL,
  wallet_id uuid NOT NULL REFERENCES public.tyapp_yyems_wallet (tb_tyapp_ywl_id),
  -- Set to cty or frd's tyapp_user.user_id. NULL = shared 50/50 (legacy "yyems").
  ownership_user_id uuid REFERENCES public.tyapp_user (user_id),
  remark text,
  description text,
  reconciled boolean NOT NULL DEFAULT false,
  -- When bill currency <> wallet account currency, store the wallet-side amount.
  -- Settlement uses wallet_amount if not null, else amount.
  wallet_amount numeric,
  period_start date,
  period_end date,
  created_by uuid NOT NULL REFERENCES public.tyapp_user (user_id),
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_yyems_tz_ok CHECK (location_tz IN ('HK', 'TO')),
  CONSTRAINT tyapp_yyems_flow_ok CHECK (in_or_out IN ('in', 'out', 'free'))
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyems_legacy_uniq
  ON public.tyapp_yyems (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyems_occurred_idx
  ON public.tyapp_yyems (occurred_at DESC)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyems_wallet_idx
  ON public.tyapp_yyems (wallet_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyems_ownership_idx
  ON public.tyapp_yyems (ownership_user_id)
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyems_price (
  tb_tyapp_ypr_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_ypr_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  priced_at timestamptz NOT NULL,
  vendor_id uuid REFERENCES public.tyapp_yyems_vendor (tb_tyapp_yvd_id),
  item_id uuid NOT NULL REFERENCES public.tyapp_yyems_item (tb_tyapp_yit_id),
  product_name text,
  product_name_zh text,
  brand text,
  currency text NOT NULL REFERENCES public.tyapp_yyems_currency (code),
  packed_price numeric,
  tax_rate numeric,
  discount_rate numeric,
  marked_price numeric,
  marked_amount numeric,
  marked_unit text,
  packed_amount numeric,
  packed_unit text,
  tag text,
  is_organic boolean,
  has_msg boolean,
  origin text,
  barcode text,
  barcode_type text,
  remarks text,
  nutri_basis_amount numeric,
  nutri_basis_unit text,
  protein_g numeric,
  carb_g numeric,
  fat_g numeric,
  calories_kcal numeric,
  fiber_g numeric,
  sodium_mg numeric,
  nutri_is_estimated boolean NOT NULL DEFAULT false,
  created_by uuid NOT NULL REFERENCES public.tyapp_user (user_id),
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_yyems_price_barcode_type_ok
    CHECK (
      barcode_type IS NULL
      OR barcode_type IN ('upc', 'plu', 'price_embedded')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyems_price_legacy_uniq
  ON public.tyapp_yyems_price (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyems_price_item_idx
  ON public.tyapp_yyems_price (item_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyems_price_barcode_idx
  ON public.tyapp_yyems_price (barcode)
  WHERE deleted_at IS NULL AND barcode IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyems_buy (
  tb_tyapp_yby_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yby_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  price_id uuid NOT NULL REFERENCES public.tyapp_yyems_price (tb_tyapp_ypr_id),
  yyems_id uuid REFERENCES public.tyapp_yyems (tb_tyapp_yym_id),
  paid numeric,
  home_amount numeric NOT NULL,
  home_unit text,
  marked_amount_count numeric,
  expiry_date date,
  remarks text,
  paid_adjust_note text,
  paid_adjust_reason text,
  eat_priority integer NOT NULL DEFAULT 50,
  created_by uuid NOT NULL REFERENCES public.tyapp_user (user_id),
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyems_buy_legacy_uniq
  ON public.tyapp_yyems_buy (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyems_buy_yyems_idx
  ON public.tyapp_yyems_buy (yyems_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyems_buy_price_idx
  ON public.tyapp_yyems_buy (price_id)
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyems_eat (
  tb_tyapp_yet_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yet_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  buy_id uuid NOT NULL REFERENCES public.tyapp_yyems_buy (tb_tyapp_yby_id),
  home_amount numeric NOT NULL,
  meal text NOT NULL,
  eaten_by_user_id uuid REFERENCES public.tyapp_user (user_id),
  -- When not a login: shared | dining_out | nil (legacy yyems / 外 / 無).
  eaten_by_other text,
  eat_date date NOT NULL,
  added_at timestamptz NOT NULL DEFAULT now(),
  description text,
  created_by uuid NOT NULL REFERENCES public.tyapp_user (user_id),
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_yyems_eat_meal_ok CHECK (meal IN (
    '1早', '2茶', '3午', '4茶', '5晚', '6宵', '7用', '8調', '9洗'
  )),
  CONSTRAINT tyapp_yyems_eat_eaten_by_ok CHECK (
    eaten_by_other IS NULL
    OR eaten_by_other IN ('shared', 'dining_out', 'nil')
  ),
  CONSTRAINT tyapp_yyems_eat_eaten_by_xor CHECK (
    eaten_by_user_id IS NULL OR eaten_by_other IS NULL
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyems_eat_legacy_uniq
  ON public.tyapp_yyems_eat (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyems_eat_date_idx
  ON public.tyapp_yyems_eat (eat_date DESC)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyems_eat_buy_idx
  ON public.tyapp_yyems_eat (buy_id)
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.tyapp_yyems_file (
  tb_tyapp_yfl_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tb_tyapp_yfl_seq_no bigint GENERATED BY DEFAULT AS IDENTITY,
  legacy_id text,
  yyems_id uuid NOT NULL REFERENCES public.tyapp_yyems (tb_tyapp_yym_id),
  kind text NOT NULL,
  drive_file_id text,
  legacy_path text,
  original_filename text,
  created_by uuid NOT NULL REFERENCES public.tyapp_user (user_id),
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT tyapp_yyems_file_kind_ok CHECK (kind IN ('receipt', 'photo', 'file')),
  CONSTRAINT tyapp_yyems_file_has_pointer CHECK (
    drive_file_id IS NOT NULL OR legacy_path IS NOT NULL
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS tyapp_yyems_file_legacy_uniq
  ON public.tyapp_yyems_file (legacy_id)
  WHERE legacy_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS tyapp_yyems_file_bill_idx
  ON public.tyapp_yyems_file (yyems_id)
  WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- updated_at
-- ---------------------------------------------------------------------------

DROP TRIGGER IF EXISTS tyapp_yyems_item_category_set_updated_at
  ON public.tyapp_yyems_item_category;
CREATE TRIGGER tyapp_yyems_item_category_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyems_item_category
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyems_item_set_updated_at
  ON public.tyapp_yyems_item;
CREATE TRIGGER tyapp_yyems_item_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyems_item
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyems_vendor_category_set_updated_at
  ON public.tyapp_yyems_vendor_category;
CREATE TRIGGER tyapp_yyems_vendor_category_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyems_vendor_category
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyems_vendor_set_updated_at
  ON public.tyapp_yyems_vendor;
CREATE TRIGGER tyapp_yyems_vendor_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyems_vendor
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyems_fa_set_updated_at
  ON public.tyapp_yyems_financial_account;
CREATE TRIGGER tyapp_yyems_fa_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyems_financial_account
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyems_wallet_set_updated_at
  ON public.tyapp_yyems_wallet;
CREATE TRIGGER tyapp_yyems_wallet_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyems_wallet
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyems_fx_set_updated_at
  ON public.tyapp_yyems_fx_rate;
CREATE TRIGGER tyapp_yyems_fx_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyems_fx_rate
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyems_set_updated_at
  ON public.tyapp_yyems;
CREATE TRIGGER tyapp_yyems_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyems
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyems_price_set_updated_at
  ON public.tyapp_yyems_price;
CREATE TRIGGER tyapp_yyems_price_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyems_price
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyems_buy_set_updated_at
  ON public.tyapp_yyems_buy;
CREATE TRIGGER tyapp_yyems_buy_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyems_buy
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyems_eat_set_updated_at
  ON public.tyapp_yyems_eat;
CREATE TRIGGER tyapp_yyems_eat_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyems_eat
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tyapp_yyems_file_set_updated_at
  ON public.tyapp_yyems_file;
CREATE TRIGGER tyapp_yyems_file_set_updated_at
  BEFORE INSERT OR UPDATE ON public.tyapp_yyems_file
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------------------
-- RLS: shared household ledger (both bound users see everything)
-- ---------------------------------------------------------------------------

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'tyapp_yyems_item_category',
    'tyapp_yyems_item',
    'tyapp_yyems_vendor_category',
    'tyapp_yyems_vendor',
    'tyapp_yyems_currency',
    'tyapp_yyems_financial_account',
    'tyapp_yyems_wallet',
    'tyapp_yyems_fx_rate',
    'tyapp_yyems',
    'tyapp_yyems_price',
    'tyapp_yyems_buy',
    'tyapp_yyems_eat',
    'tyapp_yyems_file'
  ]
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC, anon', t);
    IF t = 'tyapp_yyems_currency' THEN
      EXECUTE format(
        'GRANT SELECT, INSERT, UPDATE ON public.%I TO authenticated',
        t
      );
    ELSE
      EXECUTE format(
        'GRANT SELECT, INSERT, UPDATE ON public.%I TO authenticated',
        t
      );
    END IF;
  END LOOP;
END;
$$;

DROP POLICY IF EXISTS tyapp_yyems_currency_select ON public.tyapp_yyems_currency;
CREATE POLICY tyapp_yyems_currency_select
  ON public.tyapp_yyems_currency
  FOR SELECT TO authenticated
  USING (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_currency_write ON public.tyapp_yyems_currency;
CREATE POLICY tyapp_yyems_currency_write
  ON public.tyapp_yyems_currency
  FOR ALL TO authenticated
  USING (public.tyapp_yyems_is_household_member())
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_select_item_category
  ON public.tyapp_yyems_item_category;
CREATE POLICY tyapp_yyems_household_select_item_category
  ON public.tyapp_yyems_item_category
  FOR SELECT TO authenticated
  USING (public.tyapp_yyems_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyems_household_ins_item_category
  ON public.tyapp_yyems_item_category;
CREATE POLICY tyapp_yyems_household_ins_item_category
  ON public.tyapp_yyems_item_category
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_upd_item_category
  ON public.tyapp_yyems_item_category;
CREATE POLICY tyapp_yyems_household_upd_item_category
  ON public.tyapp_yyems_item_category
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyems_is_household_member())
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_select_item ON public.tyapp_yyems_item;
CREATE POLICY tyapp_yyems_household_select_item
  ON public.tyapp_yyems_item
  FOR SELECT TO authenticated
  USING (public.tyapp_yyems_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyems_household_ins_item ON public.tyapp_yyems_item;
CREATE POLICY tyapp_yyems_household_ins_item
  ON public.tyapp_yyems_item
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_upd_item ON public.tyapp_yyems_item;
CREATE POLICY tyapp_yyems_household_upd_item
  ON public.tyapp_yyems_item
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyems_is_household_member())
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_select_vendor_category
  ON public.tyapp_yyems_vendor_category;
CREATE POLICY tyapp_yyems_household_select_vendor_category
  ON public.tyapp_yyems_vendor_category
  FOR SELECT TO authenticated
  USING (public.tyapp_yyems_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyems_household_ins_vendor_category
  ON public.tyapp_yyems_vendor_category;
CREATE POLICY tyapp_yyems_household_ins_vendor_category
  ON public.tyapp_yyems_vendor_category
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_upd_vendor_category
  ON public.tyapp_yyems_vendor_category;
CREATE POLICY tyapp_yyems_household_upd_vendor_category
  ON public.tyapp_yyems_vendor_category
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyems_is_household_member())
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_select_vendor
  ON public.tyapp_yyems_vendor;
CREATE POLICY tyapp_yyems_household_select_vendor
  ON public.tyapp_yyems_vendor
  FOR SELECT TO authenticated
  USING (public.tyapp_yyems_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyems_household_ins_vendor
  ON public.tyapp_yyems_vendor;
CREATE POLICY tyapp_yyems_household_ins_vendor
  ON public.tyapp_yyems_vendor
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_upd_vendor
  ON public.tyapp_yyems_vendor;
CREATE POLICY tyapp_yyems_household_upd_vendor
  ON public.tyapp_yyems_vendor
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyems_is_household_member())
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_select_fa
  ON public.tyapp_yyems_financial_account;
CREATE POLICY tyapp_yyems_household_select_fa
  ON public.tyapp_yyems_financial_account
  FOR SELECT TO authenticated
  USING (public.tyapp_yyems_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyems_household_ins_fa
  ON public.tyapp_yyems_financial_account;
CREATE POLICY tyapp_yyems_household_ins_fa
  ON public.tyapp_yyems_financial_account
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_upd_fa
  ON public.tyapp_yyems_financial_account;
CREATE POLICY tyapp_yyems_household_upd_fa
  ON public.tyapp_yyems_financial_account
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyems_is_household_member())
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_select_wallet
  ON public.tyapp_yyems_wallet;
CREATE POLICY tyapp_yyems_household_select_wallet
  ON public.tyapp_yyems_wallet
  FOR SELECT TO authenticated
  USING (public.tyapp_yyems_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyems_household_ins_wallet
  ON public.tyapp_yyems_wallet;
CREATE POLICY tyapp_yyems_household_ins_wallet
  ON public.tyapp_yyems_wallet
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_upd_wallet
  ON public.tyapp_yyems_wallet;
CREATE POLICY tyapp_yyems_household_upd_wallet
  ON public.tyapp_yyems_wallet
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyems_is_household_member())
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_select_fx
  ON public.tyapp_yyems_fx_rate;
CREATE POLICY tyapp_yyems_household_select_fx
  ON public.tyapp_yyems_fx_rate
  FOR SELECT TO authenticated
  USING (public.tyapp_yyems_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyems_household_ins_fx
  ON public.tyapp_yyems_fx_rate;
CREATE POLICY tyapp_yyems_household_ins_fx
  ON public.tyapp_yyems_fx_rate
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_upd_fx
  ON public.tyapp_yyems_fx_rate;
CREATE POLICY tyapp_yyems_household_upd_fx
  ON public.tyapp_yyems_fx_rate
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyems_is_household_member())
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_select_bill ON public.tyapp_yyems;
CREATE POLICY tyapp_yyems_household_select_bill
  ON public.tyapp_yyems
  FOR SELECT TO authenticated
  USING (public.tyapp_yyems_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyems_household_ins_bill ON public.tyapp_yyems;
CREATE POLICY tyapp_yyems_household_ins_bill
  ON public.tyapp_yyems
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_upd_bill ON public.tyapp_yyems;
CREATE POLICY tyapp_yyems_household_upd_bill
  ON public.tyapp_yyems
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyems_is_household_member())
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_select_price
  ON public.tyapp_yyems_price;
CREATE POLICY tyapp_yyems_household_select_price
  ON public.tyapp_yyems_price
  FOR SELECT TO authenticated
  USING (public.tyapp_yyems_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyems_household_ins_price
  ON public.tyapp_yyems_price;
CREATE POLICY tyapp_yyems_household_ins_price
  ON public.tyapp_yyems_price
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_upd_price
  ON public.tyapp_yyems_price;
CREATE POLICY tyapp_yyems_household_upd_price
  ON public.tyapp_yyems_price
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyems_is_household_member())
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_select_buy
  ON public.tyapp_yyems_buy;
CREATE POLICY tyapp_yyems_household_select_buy
  ON public.tyapp_yyems_buy
  FOR SELECT TO authenticated
  USING (public.tyapp_yyems_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyems_household_ins_buy
  ON public.tyapp_yyems_buy;
CREATE POLICY tyapp_yyems_household_ins_buy
  ON public.tyapp_yyems_buy
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_upd_buy
  ON public.tyapp_yyems_buy;
CREATE POLICY tyapp_yyems_household_upd_buy
  ON public.tyapp_yyems_buy
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyems_is_household_member())
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_select_eat
  ON public.tyapp_yyems_eat;
CREATE POLICY tyapp_yyems_household_select_eat
  ON public.tyapp_yyems_eat
  FOR SELECT TO authenticated
  USING (public.tyapp_yyems_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyems_household_ins_eat
  ON public.tyapp_yyems_eat;
CREATE POLICY tyapp_yyems_household_ins_eat
  ON public.tyapp_yyems_eat
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_upd_eat
  ON public.tyapp_yyems_eat;
CREATE POLICY tyapp_yyems_household_upd_eat
  ON public.tyapp_yyems_eat
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyems_is_household_member())
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_select_file
  ON public.tyapp_yyems_file;
CREATE POLICY tyapp_yyems_household_select_file
  ON public.tyapp_yyems_file
  FOR SELECT TO authenticated
  USING (public.tyapp_yyems_is_household_member() AND deleted_at IS NULL);

DROP POLICY IF EXISTS tyapp_yyems_household_ins_file
  ON public.tyapp_yyems_file;
CREATE POLICY tyapp_yyems_household_ins_file
  ON public.tyapp_yyems_file
  FOR INSERT TO authenticated
  WITH CHECK (public.tyapp_yyems_is_household_member());

DROP POLICY IF EXISTS tyapp_yyems_household_upd_file
  ON public.tyapp_yyems_file;
CREATE POLICY tyapp_yyems_household_upd_file
  ON public.tyapp_yyems_file
  FOR UPDATE TO authenticated
  USING (public.tyapp_yyems_is_household_member())
  WITH CHECK (public.tyapp_yyems_is_household_member());

-- ---------------------------------------------------------------------------
-- Soft delete (no hard DELETE). Household members may delete any row.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.tyapp_yyems_soft_delete_single_record(record_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF NOT public.tyapp_yyems_is_household_member() THEN
    RAISE EXCEPTION 'Not a 525 household member';
  END IF;
  UPDATE public.tyapp_yyems
  SET deleted_at = now()
  WHERE tb_tyapp_yym_id = record_id AND deleted_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.tyapp_yyems_price_soft_delete_single_record(record_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF NOT public.tyapp_yyems_is_household_member() THEN
    RAISE EXCEPTION 'Not a 525 household member';
  END IF;
  UPDATE public.tyapp_yyems_price
  SET deleted_at = now()
  WHERE tb_tyapp_ypr_id = record_id AND deleted_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.tyapp_yyems_buy_soft_delete_single_record(record_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF NOT public.tyapp_yyems_is_household_member() THEN
    RAISE EXCEPTION 'Not a 525 household member';
  END IF;
  UPDATE public.tyapp_yyems_buy
  SET deleted_at = now()
  WHERE tb_tyapp_yby_id = record_id AND deleted_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.tyapp_yyems_eat_soft_delete_single_record(record_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF NOT public.tyapp_yyems_is_household_member() THEN
    RAISE EXCEPTION 'Not a 525 household member';
  END IF;
  UPDATE public.tyapp_yyems_eat
  SET deleted_at = now()
  WHERE tb_tyapp_yet_id = record_id AND deleted_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.tyapp_yyems_file_soft_delete_single_record(record_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;
  IF NOT public.tyapp_yyems_is_household_member() THEN
    RAISE EXCEPTION 'Not a 525 household member';
  END IF;
  UPDATE public.tyapp_yyems_file
  SET deleted_at = now()
  WHERE tb_tyapp_yfl_id = record_id AND deleted_at IS NULL;
END;
$$;

GRANT EXECUTE ON FUNCTION public.tyapp_yyems_soft_delete_single_record(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tyapp_yyems_price_soft_delete_single_record(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tyapp_yyems_buy_soft_delete_single_record(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tyapp_yyems_eat_soft_delete_single_record(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tyapp_yyems_file_soft_delete_single_record(uuid) TO authenticated;

-- Seed codes used by the AppSheet backup (import will reference these).
INSERT INTO public.tyapp_yyems_currency (code, symbol)
VALUES
  ('CAD', 'CA$'),
  ('HKD', 'HK$'),
  ('USD', 'US$'),
  ('CNY', 'CN¥'),
  ('MOP', 'MOP'),
  ('FREE', 'FREE')
ON CONFLICT (code) DO NOTHING;
